# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.  Permission to copy, use,        *
#  *     modify, sell, and distribute this software is granted provided       *
#  *     this copyright notice appears in all copies.  This software is       *
#  *     provided "as is" without express or implied warranty, and with       *
#  *     no claim at to its suitability for any purpose.                      *
#  *                                                                          *
#  ************************************************************************** */
#
# line BOOST_PP_DETAIL_LINE(flags 3 = (BOOST_PP_VALUE))
#
# ifndef BOOST_PP_VALUE
#   error BOOST_PP:  BOOST_PP_VALUE must be set prior to including BOOST_PP_SET_FLAGS()
# endif
#
# undef BOOST_PP_ITERATION_FLAGS_3
#
# if (BOOST_PP_VALUE) == 0
#   define BOOST_PP_ITERATION_FLAGS_3 0
# elif (BOOST_PP_VALUE) == 1
#   define BOOST_PP_ITERATION_FLAGS_3 1
# elif (BOOST_PP_VALUE) == 2
#   define BOOST_PP_ITERATION_FLAGS_3 2
# elif (BOOST_PP_VALUE) == 3
#   define BOOST_PP_ITERATION_FLAGS_3 3
# elif (BOOST_PP_VALUE) == 4
#   define BOOST_PP_ITERATION_FLAGS_3 4
# elif (BOOST_PP_VALUE) == 5
#   define BOOST_PP_ITERATION_FLAGS_3 5
# elif (BOOST_PP_VALUE) == 6
#   define BOOST_PP_ITERATION_FLAGS_3 6
# elif (BOOST_PP_VALUE) == 7
#   define BOOST_PP_ITERATION_FLAGS_3 7
# elif (BOOST_PP_VALUE) == 8
#   define BOOST_PP_ITERATION_FLAGS_3 8
# elif (BOOST_PP_VALUE) == 9
#   define BOOST_PP_ITERATION_FLAGS_3 9
# elif (BOOST_PP_VALUE) == 10
#   define BOOST_PP_ITERATION_FLAGS_3 10
# elif (BOOST_PP_VALUE) == 11
#   define BOOST_PP_ITERATION_FLAGS_3 11
# elif (BOOST_PP_VALUE) == 12
#   define BOOST_PP_ITERATION_FLAGS_3 12
# elif (BOOST_PP_VALUE) == 13
#   define BOOST_PP_ITERATION_FLAGS_3 13
# elif (BOOST_PP_VALUE) == 14
#   define BOOST_PP_ITERATION_FLAGS_3 14
# elif (BOOST_PP_VALUE) == 15
#   define BOOST_PP_ITERATION_FLAGS_3 15
# elif (BOOST_PP_VALUE) == 16
#   define BOOST_PP_ITERATION_FLAGS_3 16
# elif (BOOST_PP_VALUE) == 17
#   define BOOST_PP_ITERATION_FLAGS_3 17
# elif (BOOST_PP_VALUE) == 18
#   define BOOST_PP_ITERATION_FLAGS_3 18
# elif (BOOST_PP_VALUE) == 19
#   define BOOST_PP_ITERATION_FLAGS_3 19
# elif (BOOST_PP_VALUE) == 20
#   define BOOST_PP_ITERATION_FLAGS_3 20
# elif (BOOST_PP_VALUE) == 21
#   define BOOST_PP_ITERATION_FLAGS_3 21
# elif (BOOST_PP_VALUE) == 22
#   define BOOST_PP_ITERATION_FLAGS_3 22
# elif (BOOST_PP_VALUE) == 23
#   define BOOST_PP_ITERATION_FLAGS_3 23
# elif (BOOST_PP_VALUE) == 24
#   define BOOST_PP_ITERATION_FLAGS_3 24
# elif (BOOST_PP_VALUE) == 25
#   define BOOST_PP_ITERATION_FLAGS_3 25
# elif (BOOST_PP_VALUE) == 26
#   define BOOST_PP_ITERATION_FLAGS_3 26
# elif (BOOST_PP_VALUE) == 27
#   define BOOST_PP_ITERATION_FLAGS_3 27
# elif (BOOST_PP_VALUE) == 28
#   define BOOST_PP_ITERATION_FLAGS_3 28
# elif (BOOST_PP_VALUE) == 29
#   define BOOST_PP_ITERATION_FLAGS_3 29
# elif (BOOST_PP_VALUE) == 30
#   define BOOST_PP_ITERATION_FLAGS_3 30
# elif (BOOST_PP_VALUE) == 31
#   define BOOST_PP_ITERATION_FLAGS_3 31
# elif (BOOST_PP_VALUE) == 32
#   define BOOST_PP_ITERATION_FLAGS_3 32
# elif (BOOST_PP_VALUE) == 33
#   define BOOST_PP_ITERATION_FLAGS_3 33
# elif (BOOST_PP_VALUE) == 34
#   define BOOST_PP_ITERATION_FLAGS_3 34
# elif (BOOST_PP_VALUE) == 35
#   define BOOST_PP_ITERATION_FLAGS_3 35
# elif (BOOST_PP_VALUE) == 36
#   define BOOST_PP_ITERATION_FLAGS_3 36
# elif (BOOST_PP_VALUE) == 37
#   define BOOST_PP_ITERATION_FLAGS_3 37
# elif (BOOST_PP_VALUE) == 38
#   define BOOST_PP_ITERATION_FLAGS_3 38
# elif (BOOST_PP_VALUE) == 39
#   define BOOST_PP_ITERATION_FLAGS_3 39
# elif (BOOST_PP_VALUE) == 40
#   define BOOST_PP_ITERATION_FLAGS_3 40
# elif (BOOST_PP_VALUE) == 41
#   define BOOST_PP_ITERATION_FLAGS_3 41
# elif (BOOST_PP_VALUE) == 42
#   define BOOST_PP_ITERATION_FLAGS_3 42
# elif (BOOST_PP_VALUE) == 43
#   define BOOST_PP_ITERATION_FLAGS_3 43
# elif (BOOST_PP_VALUE) == 44
#   define BOOST_PP_ITERATION_FLAGS_3 44
# elif (BOOST_PP_VALUE) == 45
#   define BOOST_PP_ITERATION_FLAGS_3 45
# elif (BOOST_PP_VALUE) == 46
#   define BOOST_PP_ITERATION_FLAGS_3 46
# elif (BOOST_PP_VALUE) == 47
#   define BOOST_PP_ITERATION_FLAGS_3 47
# elif (BOOST_PP_VALUE) == 48
#   define BOOST_PP_ITERATION_FLAGS_3 48
# elif (BOOST_PP_VALUE) == 49
#   define BOOST_PP_ITERATION_FLAGS_3 49
# elif (BOOST_PP_VALUE) == 50
#   define BOOST_PP_ITERATION_FLAGS_3 50
# elif (BOOST_PP_VALUE) == 51
#   define BOOST_PP_ITERATION_FLAGS_3 51
# elif (BOOST_PP_VALUE) == 52
#   define BOOST_PP_ITERATION_FLAGS_3 52
# elif (BOOST_PP_VALUE) == 53
#   define BOOST_PP_ITERATION_FLAGS_3 53
# elif (BOOST_PP_VALUE) == 54
#   define BOOST_PP_ITERATION_FLAGS_3 54
# elif (BOOST_PP_VALUE) == 55
#   define BOOST_PP_ITERATION_FLAGS_3 55
# elif (BOOST_PP_VALUE) == 56
#   define BOOST_PP_ITERATION_FLAGS_3 56
# elif (BOOST_PP_VALUE) == 57
#   define BOOST_PP_ITERATION_FLAGS_3 57
# elif (BOOST_PP_VALUE) == 58
#   define BOOST_PP_ITERATION_FLAGS_3 58
# elif (BOOST_PP_VALUE) == 59
#   define BOOST_PP_ITERATION_FLAGS_3 59
# elif (BOOST_PP_VALUE) == 60
#   define BOOST_PP_ITERATION_FLAGS_3 60
# elif (BOOST_PP_VALUE) == 61
#   define BOOST_PP_ITERATION_FLAGS_3 61
# elif (BOOST_PP_VALUE) == 62
#   define BOOST_PP_ITERATION_FLAGS_3 62
# elif (BOOST_PP_VALUE) == 63
#   define BOOST_PP_ITERATION_FLAGS_3 63
# elif (BOOST_PP_VALUE) == 64
#   define BOOST_PP_ITERATION_FLAGS_3 64
# elif (BOOST_PP_VALUE) == 65
#   define BOOST_PP_ITERATION_FLAGS_3 65
# elif (BOOST_PP_VALUE) == 66
#   define BOOST_PP_ITERATION_FLAGS_3 66
# elif (BOOST_PP_VALUE) == 67
#   define BOOST_PP_ITERATION_FLAGS_3 67
# elif (BOOST_PP_VALUE) == 68
#   define BOOST_PP_ITERATION_FLAGS_3 68
# elif (BOOST_PP_VALUE) == 69
#   define BOOST_PP_ITERATION_FLAGS_3 69
# elif (BOOST_PP_VALUE) == 70
#   define BOOST_PP_ITERATION_FLAGS_3 70
# elif (BOOST_PP_VALUE) == 71
#   define BOOST_PP_ITERATION_FLAGS_3 71
# elif (BOOST_PP_VALUE) == 72
#   define BOOST_PP_ITERATION_FLAGS_3 72
# elif (BOOST_PP_VALUE) == 73
#   define BOOST_PP_ITERATION_FLAGS_3 73
# elif (BOOST_PP_VALUE) == 74
#   define BOOST_PP_ITERATION_FLAGS_3 74
# elif (BOOST_PP_VALUE) == 75
#   define BOOST_PP_ITERATION_FLAGS_3 75
# elif (BOOST_PP_VALUE) == 76
#   define BOOST_PP_ITERATION_FLAGS_3 76
# elif (BOOST_PP_VALUE) == 77
#   define BOOST_PP_ITERATION_FLAGS_3 77
# elif (BOOST_PP_VALUE) == 78
#   define BOOST_PP_ITERATION_FLAGS_3 78
# elif (BOOST_PP_VALUE) == 79
#   define BOOST_PP_ITERATION_FLAGS_3 79
# elif (BOOST_PP_VALUE) == 80
#   define BOOST_PP_ITERATION_FLAGS_3 80
# elif (BOOST_PP_VALUE) == 81
#   define BOOST_PP_ITERATION_FLAGS_3 81
# elif (BOOST_PP_VALUE) == 82
#   define BOOST_PP_ITERATION_FLAGS_3 82
# elif (BOOST_PP_VALUE) == 83
#   define BOOST_PP_ITERATION_FLAGS_3 83
# elif (BOOST_PP_VALUE) == 84
#   define BOOST_PP_ITERATION_FLAGS_3 84
# elif (BOOST_PP_VALUE) == 85
#   define BOOST_PP_ITERATION_FLAGS_3 85
# elif (BOOST_PP_VALUE) == 86
#   define BOOST_PP_ITERATION_FLAGS_3 86
# elif (BOOST_PP_VALUE) == 87
#   define BOOST_PP_ITERATION_FLAGS_3 87
# elif (BOOST_PP_VALUE) == 88
#   define BOOST_PP_ITERATION_FLAGS_3 88
# elif (BOOST_PP_VALUE) == 89
#   define BOOST_PP_ITERATION_FLAGS_3 89
# elif (BOOST_PP_VALUE) == 90
#   define BOOST_PP_ITERATION_FLAGS_3 90
# elif (BOOST_PP_VALUE) == 91
#   define BOOST_PP_ITERATION_FLAGS_3 91
# elif (BOOST_PP_VALUE) == 92
#   define BOOST_PP_ITERATION_FLAGS_3 92
# elif (BOOST_PP_VALUE) == 93
#   define BOOST_PP_ITERATION_FLAGS_3 93
# elif (BOOST_PP_VALUE) == 94
#   define BOOST_PP_ITERATION_FLAGS_3 94
# elif (BOOST_PP_VALUE) == 95
#   define BOOST_PP_ITERATION_FLAGS_3 95
# elif (BOOST_PP_VALUE) == 96
#   define BOOST_PP_ITERATION_FLAGS_3 96
# elif (BOOST_PP_VALUE) == 97
#   define BOOST_PP_ITERATION_FLAGS_3 97
# elif (BOOST_PP_VALUE) == 98
#   define BOOST_PP_ITERATION_FLAGS_3 98
# elif (BOOST_PP_VALUE) == 99
#   define BOOST_PP_ITERATION_FLAGS_3 99
# elif (BOOST_PP_VALUE) == 100
#   define BOOST_PP_ITERATION_FLAGS_3 100
# elif (BOOST_PP_VALUE) == 101
#   define BOOST_PP_ITERATION_FLAGS_3 101
# elif (BOOST_PP_VALUE) == 102
#   define BOOST_PP_ITERATION_FLAGS_3 102
# elif (BOOST_PP_VALUE) == 103
#   define BOOST_PP_ITERATION_FLAGS_3 103
# elif (BOOST_PP_VALUE) == 104
#   define BOOST_PP_ITERATION_FLAGS_3 104
# elif (BOOST_PP_VALUE) == 105
#   define BOOST_PP_ITERATION_FLAGS_3 105
# elif (BOOST_PP_VALUE) == 106
#   define BOOST_PP_ITERATION_FLAGS_3 106
# elif (BOOST_PP_VALUE) == 107
#   define BOOST_PP_ITERATION_FLAGS_3 107
# elif (BOOST_PP_VALUE) == 108
#   define BOOST_PP_ITERATION_FLAGS_3 108
# elif (BOOST_PP_VALUE) == 109
#   define BOOST_PP_ITERATION_FLAGS_3 109
# elif (BOOST_PP_VALUE) == 110
#   define BOOST_PP_ITERATION_FLAGS_3 110
# elif (BOOST_PP_VALUE) == 111
#   define BOOST_PP_ITERATION_FLAGS_3 111
# elif (BOOST_PP_VALUE) == 112
#   define BOOST_PP_ITERATION_FLAGS_3 112
# elif (BOOST_PP_VALUE) == 113
#   define BOOST_PP_ITERATION_FLAGS_3 113
# elif (BOOST_PP_VALUE) == 114
#   define BOOST_PP_ITERATION_FLAGS_3 114
# elif (BOOST_PP_VALUE) == 115
#   define BOOST_PP_ITERATION_FLAGS_3 115
# elif (BOOST_PP_VALUE) == 116
#   define BOOST_PP_ITERATION_FLAGS_3 116
# elif (BOOST_PP_VALUE) == 117
#   define BOOST_PP_ITERATION_FLAGS_3 117
# elif (BOOST_PP_VALUE) == 118
#   define BOOST_PP_ITERATION_FLAGS_3 118
# elif (BOOST_PP_VALUE) == 119
#   define BOOST_PP_ITERATION_FLAGS_3 119
# elif (BOOST_PP_VALUE) == 120
#   define BOOST_PP_ITERATION_FLAGS_3 120
# elif (BOOST_PP_VALUE) == 121
#   define BOOST_PP_ITERATION_FLAGS_3 121
# elif (BOOST_PP_VALUE) == 122
#   define BOOST_PP_ITERATION_FLAGS_3 122
# elif (BOOST_PP_VALUE) == 123
#   define BOOST_PP_ITERATION_FLAGS_3 123
# elif (BOOST_PP_VALUE) == 124
#   define BOOST_PP_ITERATION_FLAGS_3 124
# elif (BOOST_PP_VALUE) == 125
#   define BOOST_PP_ITERATION_FLAGS_3 125
# elif (BOOST_PP_VALUE) == 126
#   define BOOST_PP_ITERATION_FLAGS_3 126
# elif (BOOST_PP_VALUE) == 127
#   define BOOST_PP_ITERATION_FLAGS_3 127
# elif (BOOST_PP_VALUE) == 128
#   define BOOST_PP_ITERATION_FLAGS_3 128
# elif (BOOST_PP_VALUE) == 129
#   define BOOST_PP_ITERATION_FLAGS_3 129
# elif (BOOST_PP_VALUE) == 130
#   define BOOST_PP_ITERATION_FLAGS_3 130
# elif (BOOST_PP_VALUE) == 131
#   define BOOST_PP_ITERATION_FLAGS_3 131
# elif (BOOST_PP_VALUE) == 132
#   define BOOST_PP_ITERATION_FLAGS_3 132
# elif (BOOST_PP_VALUE) == 133
#   define BOOST_PP_ITERATION_FLAGS_3 133
# elif (BOOST_PP_VALUE) == 134
#   define BOOST_PP_ITERATION_FLAGS_3 134
# elif (BOOST_PP_VALUE) == 135
#   define BOOST_PP_ITERATION_FLAGS_3 135
# elif (BOOST_PP_VALUE) == 136
#   define BOOST_PP_ITERATION_FLAGS_3 136
# elif (BOOST_PP_VALUE) == 137
#   define BOOST_PP_ITERATION_FLAGS_3 137
# elif (BOOST_PP_VALUE) == 138
#   define BOOST_PP_ITERATION_FLAGS_3 138
# elif (BOOST_PP_VALUE) == 139
#   define BOOST_PP_ITERATION_FLAGS_3 139
# elif (BOOST_PP_VALUE) == 140
#   define BOOST_PP_ITERATION_FLAGS_3 140
# elif (BOOST_PP_VALUE) == 141
#   define BOOST_PP_ITERATION_FLAGS_3 141
# elif (BOOST_PP_VALUE) == 142
#   define BOOST_PP_ITERATION_FLAGS_3 142
# elif (BOOST_PP_VALUE) == 143
#   define BOOST_PP_ITERATION_FLAGS_3 143
# elif (BOOST_PP_VALUE) == 144
#   define BOOST_PP_ITERATION_FLAGS_3 144
# elif (BOOST_PP_VALUE) == 145
#   define BOOST_PP_ITERATION_FLAGS_3 145
# elif (BOOST_PP_VALUE) == 146
#   define BOOST_PP_ITERATION_FLAGS_3 146
# elif (BOOST_PP_VALUE) == 147
#   define BOOST_PP_ITERATION_FLAGS_3 147
# elif (BOOST_PP_VALUE) == 148
#   define BOOST_PP_ITERATION_FLAGS_3 148
# elif (BOOST_PP_VALUE) == 149
#   define BOOST_PP_ITERATION_FLAGS_3 149
# elif (BOOST_PP_VALUE) == 150
#   define BOOST_PP_ITERATION_FLAGS_3 150
# elif (BOOST_PP_VALUE) == 151
#   define BOOST_PP_ITERATION_FLAGS_3 151
# elif (BOOST_PP_VALUE) == 152
#   define BOOST_PP_ITERATION_FLAGS_3 152
# elif (BOOST_PP_VALUE) == 153
#   define BOOST_PP_ITERATION_FLAGS_3 153
# elif (BOOST_PP_VALUE) == 154
#   define BOOST_PP_ITERATION_FLAGS_3 154
# elif (BOOST_PP_VALUE) == 155
#   define BOOST_PP_ITERATION_FLAGS_3 155
# elif (BOOST_PP_VALUE) == 156
#   define BOOST_PP_ITERATION_FLAGS_3 156
# elif (BOOST_PP_VALUE) == 157
#   define BOOST_PP_ITERATION_FLAGS_3 157
# elif (BOOST_PP_VALUE) == 158
#   define BOOST_PP_ITERATION_FLAGS_3 158
# elif (BOOST_PP_VALUE) == 159
#   define BOOST_PP_ITERATION_FLAGS_3 159
# elif (BOOST_PP_VALUE) == 160
#   define BOOST_PP_ITERATION_FLAGS_3 160
# elif (BOOST_PP_VALUE) == 161
#   define BOOST_PP_ITERATION_FLAGS_3 161
# elif (BOOST_PP_VALUE) == 162
#   define BOOST_PP_ITERATION_FLAGS_3 162
# elif (BOOST_PP_VALUE) == 163
#   define BOOST_PP_ITERATION_FLAGS_3 163
# elif (BOOST_PP_VALUE) == 164
#   define BOOST_PP_ITERATION_FLAGS_3 164
# elif (BOOST_PP_VALUE) == 165
#   define BOOST_PP_ITERATION_FLAGS_3 165
# elif (BOOST_PP_VALUE) == 166
#   define BOOST_PP_ITERATION_FLAGS_3 166
# elif (BOOST_PP_VALUE) == 167
#   define BOOST_PP_ITERATION_FLAGS_3 167
# elif (BOOST_PP_VALUE) == 168
#   define BOOST_PP_ITERATION_FLAGS_3 168
# elif (BOOST_PP_VALUE) == 169
#   define BOOST_PP_ITERATION_FLAGS_3 169
# elif (BOOST_PP_VALUE) == 170
#   define BOOST_PP_ITERATION_FLAGS_3 170
# elif (BOOST_PP_VALUE) == 171
#   define BOOST_PP_ITERATION_FLAGS_3 171
# elif (BOOST_PP_VALUE) == 172
#   define BOOST_PP_ITERATION_FLAGS_3 172
# elif (BOOST_PP_VALUE) == 173
#   define BOOST_PP_ITERATION_FLAGS_3 173
# elif (BOOST_PP_VALUE) == 174
#   define BOOST_PP_ITERATION_FLAGS_3 174
# elif (BOOST_PP_VALUE) == 175
#   define BOOST_PP_ITERATION_FLAGS_3 175
# elif (BOOST_PP_VALUE) == 176
#   define BOOST_PP_ITERATION_FLAGS_3 176
# elif (BOOST_PP_VALUE) == 177
#   define BOOST_PP_ITERATION_FLAGS_3 177
# elif (BOOST_PP_VALUE) == 178
#   define BOOST_PP_ITERATION_FLAGS_3 178
# elif (BOOST_PP_VALUE) == 179
#   define BOOST_PP_ITERATION_FLAGS_3 179
# elif (BOOST_PP_VALUE) == 180
#   define BOOST_PP_ITERATION_FLAGS_3 180
# elif (BOOST_PP_VALUE) == 181
#   define BOOST_PP_ITERATION_FLAGS_3 181
# elif (BOOST_PP_VALUE) == 182
#   define BOOST_PP_ITERATION_FLAGS_3 182
# elif (BOOST_PP_VALUE) == 183
#   define BOOST_PP_ITERATION_FLAGS_3 183
# elif (BOOST_PP_VALUE) == 184
#   define BOOST_PP_ITERATION_FLAGS_3 184
# elif (BOOST_PP_VALUE) == 185
#   define BOOST_PP_ITERATION_FLAGS_3 185
# elif (BOOST_PP_VALUE) == 186
#   define BOOST_PP_ITERATION_FLAGS_3 186
# elif (BOOST_PP_VALUE) == 187
#   define BOOST_PP_ITERATION_FLAGS_3 187
# elif (BOOST_PP_VALUE) == 188
#   define BOOST_PP_ITERATION_FLAGS_3 188
# elif (BOOST_PP_VALUE) == 189
#   define BOOST_PP_ITERATION_FLAGS_3 189
# elif (BOOST_PP_VALUE) == 190
#   define BOOST_PP_ITERATION_FLAGS_3 190
# elif (BOOST_PP_VALUE) == 191
#   define BOOST_PP_ITERATION_FLAGS_3 191
# elif (BOOST_PP_VALUE) == 192
#   define BOOST_PP_ITERATION_FLAGS_3 192
# elif (BOOST_PP_VALUE) == 193
#   define BOOST_PP_ITERATION_FLAGS_3 193
# elif (BOOST_PP_VALUE) == 194
#   define BOOST_PP_ITERATION_FLAGS_3 194
# elif (BOOST_PP_VALUE) == 195
#   define BOOST_PP_ITERATION_FLAGS_3 195
# elif (BOOST_PP_VALUE) == 196
#   define BOOST_PP_ITERATION_FLAGS_3 196
# elif (BOOST_PP_VALUE) == 197
#   define BOOST_PP_ITERATION_FLAGS_3 197
# elif (BOOST_PP_VALUE) == 198
#   define BOOST_PP_ITERATION_FLAGS_3 198
# elif (BOOST_PP_VALUE) == 199
#   define BOOST_PP_ITERATION_FLAGS_3 199
# elif (BOOST_PP_VALUE) == 200
#   define BOOST_PP_ITERATION_FLAGS_3 200
# elif (BOOST_PP_VALUE) == 201
#   define BOOST_PP_ITERATION_FLAGS_3 201
# elif (BOOST_PP_VALUE) == 202
#   define BOOST_PP_ITERATION_FLAGS_3 202
# elif (BOOST_PP_VALUE) == 203
#   define BOOST_PP_ITERATION_FLAGS_3 203
# elif (BOOST_PP_VALUE) == 204
#   define BOOST_PP_ITERATION_FLAGS_3 204
# elif (BOOST_PP_VALUE) == 205
#   define BOOST_PP_ITERATION_FLAGS_3 205
# elif (BOOST_PP_VALUE) == 206
#   define BOOST_PP_ITERATION_FLAGS_3 206
# elif (BOOST_PP_VALUE) == 207
#   define BOOST_PP_ITERATION_FLAGS_3 207
# elif (BOOST_PP_VALUE) == 208
#   define BOOST_PP_ITERATION_FLAGS_3 208
# elif (BOOST_PP_VALUE) == 209
#   define BOOST_PP_ITERATION_FLAGS_3 209
# elif (BOOST_PP_VALUE) == 210
#   define BOOST_PP_ITERATION_FLAGS_3 210
# elif (BOOST_PP_VALUE) == 211
#   define BOOST_PP_ITERATION_FLAGS_3 211
# elif (BOOST_PP_VALUE) == 212
#   define BOOST_PP_ITERATION_FLAGS_3 212
# elif (BOOST_PP_VALUE) == 213
#   define BOOST_PP_ITERATION_FLAGS_3 213
# elif (BOOST_PP_VALUE) == 214
#   define BOOST_PP_ITERATION_FLAGS_3 214
# elif (BOOST_PP_VALUE) == 215
#   define BOOST_PP_ITERATION_FLAGS_3 215
# elif (BOOST_PP_VALUE) == 216
#   define BOOST_PP_ITERATION_FLAGS_3 216
# elif (BOOST_PP_VALUE) == 217
#   define BOOST_PP_ITERATION_FLAGS_3 217
# elif (BOOST_PP_VALUE) == 218
#   define BOOST_PP_ITERATION_FLAGS_3 218
# elif (BOOST_PP_VALUE) == 219
#   define BOOST_PP_ITERATION_FLAGS_3 219
# elif (BOOST_PP_VALUE) == 220
#   define BOOST_PP_ITERATION_FLAGS_3 220
# elif (BOOST_PP_VALUE) == 221
#   define BOOST_PP_ITERATION_FLAGS_3 221
# elif (BOOST_PP_VALUE) == 222
#   define BOOST_PP_ITERATION_FLAGS_3 222
# elif (BOOST_PP_VALUE) == 223
#   define BOOST_PP_ITERATION_FLAGS_3 223
# elif (BOOST_PP_VALUE) == 224
#   define BOOST_PP_ITERATION_FLAGS_3 224
# elif (BOOST_PP_VALUE) == 225
#   define BOOST_PP_ITERATION_FLAGS_3 225
# elif (BOOST_PP_VALUE) == 226
#   define BOOST_PP_ITERATION_FLAGS_3 226
# elif (BOOST_PP_VALUE) == 227
#   define BOOST_PP_ITERATION_FLAGS_3 227
# elif (BOOST_PP_VALUE) == 228
#   define BOOST_PP_ITERATION_FLAGS_3 228
# elif (BOOST_PP_VALUE) == 229
#   define BOOST_PP_ITERATION_FLAGS_3 229
# elif (BOOST_PP_VALUE) == 230
#   define BOOST_PP_ITERATION_FLAGS_3 230
# elif (BOOST_PP_VALUE) == 231
#   define BOOST_PP_ITERATION_FLAGS_3 231
# elif (BOOST_PP_VALUE) == 232
#   define BOOST_PP_ITERATION_FLAGS_3 232
# elif (BOOST_PP_VALUE) == 233
#   define BOOST_PP_ITERATION_FLAGS_3 233
# elif (BOOST_PP_VALUE) == 234
#   define BOOST_PP_ITERATION_FLAGS_3 234
# elif (BOOST_PP_VALUE) == 235
#   define BOOST_PP_ITERATION_FLAGS_3 235
# elif (BOOST_PP_VALUE) == 236
#   define BOOST_PP_ITERATION_FLAGS_3 236
# elif (BOOST_PP_VALUE) == 237
#   define BOOST_PP_ITERATION_FLAGS_3 237
# elif (BOOST_PP_VALUE) == 238
#   define BOOST_PP_ITERATION_FLAGS_3 238
# elif (BOOST_PP_VALUE) == 239
#   define BOOST_PP_ITERATION_FLAGS_3 239
# elif (BOOST_PP_VALUE) == 240
#   define BOOST_PP_ITERATION_FLAGS_3 240
# elif (BOOST_PP_VALUE) == 241
#   define BOOST_PP_ITERATION_FLAGS_3 241
# elif (BOOST_PP_VALUE) == 242
#   define BOOST_PP_ITERATION_FLAGS_3 242
# elif (BOOST_PP_VALUE) == 243
#   define BOOST_PP_ITERATION_FLAGS_3 243
# elif (BOOST_PP_VALUE) == 244
#   define BOOST_PP_ITERATION_FLAGS_3 244
# elif (BOOST_PP_VALUE) == 245
#   define BOOST_PP_ITERATION_FLAGS_3 245
# elif (BOOST_PP_VALUE) == 246
#   define BOOST_PP_ITERATION_FLAGS_3 246
# elif (BOOST_PP_VALUE) == 247
#   define BOOST_PP_ITERATION_FLAGS_3 247
# elif (BOOST_PP_VALUE) == 248
#   define BOOST_PP_ITERATION_FLAGS_3 248
# elif (BOOST_PP_VALUE) == 249
#   define BOOST_PP_ITERATION_FLAGS_3 249
# elif (BOOST_PP_VALUE) == 250
#   define BOOST_PP_ITERATION_FLAGS_3 250
# elif (BOOST_PP_VALUE) == 251
#   define BOOST_PP_ITERATION_FLAGS_3 251
# elif (BOOST_PP_VALUE) == 252
#   define BOOST_PP_ITERATION_FLAGS_3 252
# elif (BOOST_PP_VALUE) == 253
#   define BOOST_PP_ITERATION_FLAGS_3 253
# elif (BOOST_PP_VALUE) == 254
#   define BOOST_PP_ITERATION_FLAGS_3 254
# elif (BOOST_PP_VALUE) == 255
#   define BOOST_PP_ITERATION_FLAGS_3 255
# elif (BOOST_PP_VALUE) == 256
#   define BOOST_PP_ITERATION_FLAGS_3 256
# else
#   error BOOST_PP:  BOOST_PP_VALUE is out of range
# endif
#
# undef BOOST_PP_VALUE
