# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.  Permission to copy, use,        *
#  *     modify, sell, and distribute this software is granted provided       *
#  *     this copyright notice appears in all copies.  This software is       *
#  *     provided "as is" without express or implied warranty, and with       *
#  *     no claim at to its suitability for any purpose.                      *
#  *                                                                          *
#  ************************************************************************** */
#
# ifdef BOOST_PP_LOCAL_LIMITS
#   define BOOST_PP_LOCAL_START BOOST_PP_TUPLE_ELEM(2, 0, BOOST_PP_LOCAL_LIMITS)
#   define BOOST_PP_LOCAL_FINISH BOOST_PP_TUPLE_ELEM(2, 1, BOOST_PP_LOCAL_LIMITS)
# else
#   error BOOST_PP:  local iteration boundaries are not defined
# endif
#
# if (BOOST_PP_LOCAL_START) <= 0 && (BOOST_PP_LOCAL_FINISH) >= 0
    BOOST_PP_LOCAL_MACRO(0)
# endif
# if (BOOST_PP_LOCAL_START) <= 1 && (BOOST_PP_LOCAL_FINISH) >= 1
    BOOST_PP_LOCAL_MACRO(1)
# endif
# if (BOOST_PP_LOCAL_START) <= 2 && (BOOST_PP_LOCAL_FINISH) >= 2
    BOOST_PP_LOCAL_MACRO(2)
# endif
# if (BOOST_PP_LOCAL_START) <= 3 && (BOOST_PP_LOCAL_FINISH) >= 3
    BOOST_PP_LOCAL_MACRO(3)
# endif
# if (BOOST_PP_LOCAL_START) <= 4 && (BOOST_PP_LOCAL_FINISH) >= 4
    BOOST_PP_LOCAL_MACRO(4)
# endif
# if (BOOST_PP_LOCAL_START) <= 5 && (BOOST_PP_LOCAL_FINISH) >= 5
    BOOST_PP_LOCAL_MACRO(5)
# endif
# if (BOOST_PP_LOCAL_START) <= 6 && (BOOST_PP_LOCAL_FINISH) >= 6
    BOOST_PP_LOCAL_MACRO(6)
# endif
# if (BOOST_PP_LOCAL_START) <= 7 && (BOOST_PP_LOCAL_FINISH) >= 7
    BOOST_PP_LOCAL_MACRO(7)
# endif
# if (BOOST_PP_LOCAL_START) <= 8 && (BOOST_PP_LOCAL_FINISH) >= 8
    BOOST_PP_LOCAL_MACRO(8)
# endif
# if (BOOST_PP_LOCAL_START) <= 9 && (BOOST_PP_LOCAL_FINISH) >= 9
    BOOST_PP_LOCAL_MACRO(9)
# endif
# if (BOOST_PP_LOCAL_START) <= 10 && (BOOST_PP_LOCAL_FINISH) >= 10
    BOOST_PP_LOCAL_MACRO(10)
# endif
# if (BOOST_PP_LOCAL_START) <= 11 && (BOOST_PP_LOCAL_FINISH) >= 11
    BOOST_PP_LOCAL_MACRO(11)
# endif
# if (BOOST_PP_LOCAL_START) <= 12 && (BOOST_PP_LOCAL_FINISH) >= 12
    BOOST_PP_LOCAL_MACRO(12)
# endif
# if (BOOST_PP_LOCAL_START) <= 13 && (BOOST_PP_LOCAL_FINISH) >= 13
    BOOST_PP_LOCAL_MACRO(13)
# endif
# if (BOOST_PP_LOCAL_START) <= 14 && (BOOST_PP_LOCAL_FINISH) >= 14
    BOOST_PP_LOCAL_MACRO(14)
# endif
# if (BOOST_PP_LOCAL_START) <= 15 && (BOOST_PP_LOCAL_FINISH) >= 15
    BOOST_PP_LOCAL_MACRO(15)
# endif
# if (BOOST_PP_LOCAL_START) <= 16 && (BOOST_PP_LOCAL_FINISH) >= 16
    BOOST_PP_LOCAL_MACRO(16)
# endif
# if (BOOST_PP_LOCAL_START) <= 17 && (BOOST_PP_LOCAL_FINISH) >= 17
    BOOST_PP_LOCAL_MACRO(17)
# endif
# if (BOOST_PP_LOCAL_START) <= 18 && (BOOST_PP_LOCAL_FINISH) >= 18
    BOOST_PP_LOCAL_MACRO(18)
# endif
# if (BOOST_PP_LOCAL_START) <= 19 && (BOOST_PP_LOCAL_FINISH) >= 19
    BOOST_PP_LOCAL_MACRO(19)
# endif
# if (BOOST_PP_LOCAL_START) <= 20 && (BOOST_PP_LOCAL_FINISH) >= 20
    BOOST_PP_LOCAL_MACRO(20)
# endif
# if (BOOST_PP_LOCAL_START) <= 21 && (BOOST_PP_LOCAL_FINISH) >= 21
    BOOST_PP_LOCAL_MACRO(21)
# endif
# if (BOOST_PP_LOCAL_START) <= 22 && (BOOST_PP_LOCAL_FINISH) >= 22
    BOOST_PP_LOCAL_MACRO(22)
# endif
# if (BOOST_PP_LOCAL_START) <= 23 && (BOOST_PP_LOCAL_FINISH) >= 23
    BOOST_PP_LOCAL_MACRO(23)
# endif
# if (BOOST_PP_LOCAL_START) <= 24 && (BOOST_PP_LOCAL_FINISH) >= 24
    BOOST_PP_LOCAL_MACRO(24)
# endif
# if (BOOST_PP_LOCAL_START) <= 25 && (BOOST_PP_LOCAL_FINISH) >= 25
    BOOST_PP_LOCAL_MACRO(25)
# endif
# if (BOOST_PP_LOCAL_START) <= 26 && (BOOST_PP_LOCAL_FINISH) >= 26
    BOOST_PP_LOCAL_MACRO(26)
# endif
# if (BOOST_PP_LOCAL_START) <= 27 && (BOOST_PP_LOCAL_FINISH) >= 27
    BOOST_PP_LOCAL_MACRO(27)
# endif
# if (BOOST_PP_LOCAL_START) <= 28 && (BOOST_PP_LOCAL_FINISH) >= 28
    BOOST_PP_LOCAL_MACRO(28)
# endif
# if (BOOST_PP_LOCAL_START) <= 29 && (BOOST_PP_LOCAL_FINISH) >= 29
    BOOST_PP_LOCAL_MACRO(29)
# endif
# if (BOOST_PP_LOCAL_START) <= 30 && (BOOST_PP_LOCAL_FINISH) >= 30
    BOOST_PP_LOCAL_MACRO(30)
# endif
# if (BOOST_PP_LOCAL_START) <= 31 && (BOOST_PP_LOCAL_FINISH) >= 31
    BOOST_PP_LOCAL_MACRO(31)
# endif
# if (BOOST_PP_LOCAL_START) <= 32 && (BOOST_PP_LOCAL_FINISH) >= 32
    BOOST_PP_LOCAL_MACRO(32)
# endif
# if (BOOST_PP_LOCAL_START) <= 33 && (BOOST_PP_LOCAL_FINISH) >= 33
    BOOST_PP_LOCAL_MACRO(33)
# endif
# if (BOOST_PP_LOCAL_START) <= 34 && (BOOST_PP_LOCAL_FINISH) >= 34
    BOOST_PP_LOCAL_MACRO(34)
# endif
# if (BOOST_PP_LOCAL_START) <= 35 && (BOOST_PP_LOCAL_FINISH) >= 35
    BOOST_PP_LOCAL_MACRO(35)
# endif
# if (BOOST_PP_LOCAL_START) <= 36 && (BOOST_PP_LOCAL_FINISH) >= 36
    BOOST_PP_LOCAL_MACRO(36)
# endif
# if (BOOST_PP_LOCAL_START) <= 37 && (BOOST_PP_LOCAL_FINISH) >= 37
    BOOST_PP_LOCAL_MACRO(37)
# endif
# if (BOOST_PP_LOCAL_START) <= 38 && (BOOST_PP_LOCAL_FINISH) >= 38
    BOOST_PP_LOCAL_MACRO(38)
# endif
# if (BOOST_PP_LOCAL_START) <= 39 && (BOOST_PP_LOCAL_FINISH) >= 39
    BOOST_PP_LOCAL_MACRO(39)
# endif
# if (BOOST_PP_LOCAL_START) <= 40 && (BOOST_PP_LOCAL_FINISH) >= 40
    BOOST_PP_LOCAL_MACRO(40)
# endif
# if (BOOST_PP_LOCAL_START) <= 41 && (BOOST_PP_LOCAL_FINISH) >= 41
    BOOST_PP_LOCAL_MACRO(41)
# endif
# if (BOOST_PP_LOCAL_START) <= 42 && (BOOST_PP_LOCAL_FINISH) >= 42
    BOOST_PP_LOCAL_MACRO(42)
# endif
# if (BOOST_PP_LOCAL_START) <= 43 && (BOOST_PP_LOCAL_FINISH) >= 43
    BOOST_PP_LOCAL_MACRO(43)
# endif
# if (BOOST_PP_LOCAL_START) <= 44 && (BOOST_PP_LOCAL_FINISH) >= 44
    BOOST_PP_LOCAL_MACRO(44)
# endif
# if (BOOST_PP_LOCAL_START) <= 45 && (BOOST_PP_LOCAL_FINISH) >= 45
    BOOST_PP_LOCAL_MACRO(45)
# endif
# if (BOOST_PP_LOCAL_START) <= 46 && (BOOST_PP_LOCAL_FINISH) >= 46
    BOOST_PP_LOCAL_MACRO(46)
# endif
# if (BOOST_PP_LOCAL_START) <= 47 && (BOOST_PP_LOCAL_FINISH) >= 47
    BOOST_PP_LOCAL_MACRO(47)
# endif
# if (BOOST_PP_LOCAL_START) <= 48 && (BOOST_PP_LOCAL_FINISH) >= 48
    BOOST_PP_LOCAL_MACRO(48)
# endif
# if (BOOST_PP_LOCAL_START) <= 49 && (BOOST_PP_LOCAL_FINISH) >= 49
    BOOST_PP_LOCAL_MACRO(49)
# endif
# if (BOOST_PP_LOCAL_START) <= 50 && (BOOST_PP_LOCAL_FINISH) >= 50
    BOOST_PP_LOCAL_MACRO(50)
# endif
# if (BOOST_PP_LOCAL_START) <= 51 && (BOOST_PP_LOCAL_FINISH) >= 51
    BOOST_PP_LOCAL_MACRO(51)
# endif
# if (BOOST_PP_LOCAL_START) <= 52 && (BOOST_PP_LOCAL_FINISH) >= 52
    BOOST_PP_LOCAL_MACRO(52)
# endif
# if (BOOST_PP_LOCAL_START) <= 53 && (BOOST_PP_LOCAL_FINISH) >= 53
    BOOST_PP_LOCAL_MACRO(53)
# endif
# if (BOOST_PP_LOCAL_START) <= 54 && (BOOST_PP_LOCAL_FINISH) >= 54
    BOOST_PP_LOCAL_MACRO(54)
# endif
# if (BOOST_PP_LOCAL_START) <= 55 && (BOOST_PP_LOCAL_FINISH) >= 55
    BOOST_PP_LOCAL_MACRO(55)
# endif
# if (BOOST_PP_LOCAL_START) <= 56 && (BOOST_PP_LOCAL_FINISH) >= 56
    BOOST_PP_LOCAL_MACRO(56)
# endif
# if (BOOST_PP_LOCAL_START) <= 57 && (BOOST_PP_LOCAL_FINISH) >= 57
    BOOST_PP_LOCAL_MACRO(57)
# endif
# if (BOOST_PP_LOCAL_START) <= 58 && (BOOST_PP_LOCAL_FINISH) >= 58
    BOOST_PP_LOCAL_MACRO(58)
# endif
# if (BOOST_PP_LOCAL_START) <= 59 && (BOOST_PP_LOCAL_FINISH) >= 59
    BOOST_PP_LOCAL_MACRO(59)
# endif
# if (BOOST_PP_LOCAL_START) <= 60 && (BOOST_PP_LOCAL_FINISH) >= 60
    BOOST_PP_LOCAL_MACRO(60)
# endif
# if (BOOST_PP_LOCAL_START) <= 61 && (BOOST_PP_LOCAL_FINISH) >= 61
    BOOST_PP_LOCAL_MACRO(61)
# endif
# if (BOOST_PP_LOCAL_START) <= 62 && (BOOST_PP_LOCAL_FINISH) >= 62
    BOOST_PP_LOCAL_MACRO(62)
# endif
# if (BOOST_PP_LOCAL_START) <= 63 && (BOOST_PP_LOCAL_FINISH) >= 63
    BOOST_PP_LOCAL_MACRO(63)
# endif
# if (BOOST_PP_LOCAL_START) <= 64 && (BOOST_PP_LOCAL_FINISH) >= 64
    BOOST_PP_LOCAL_MACRO(64)
# endif
# if (BOOST_PP_LOCAL_START) <= 65 && (BOOST_PP_LOCAL_FINISH) >= 65
    BOOST_PP_LOCAL_MACRO(65)
# endif
# if (BOOST_PP_LOCAL_START) <= 66 && (BOOST_PP_LOCAL_FINISH) >= 66
    BOOST_PP_LOCAL_MACRO(66)
# endif
# if (BOOST_PP_LOCAL_START) <= 67 && (BOOST_PP_LOCAL_FINISH) >= 67
    BOOST_PP_LOCAL_MACRO(67)
# endif
# if (BOOST_PP_LOCAL_START) <= 68 && (BOOST_PP_LOCAL_FINISH) >= 68
    BOOST_PP_LOCAL_MACRO(68)
# endif
# if (BOOST_PP_LOCAL_START) <= 69 && (BOOST_PP_LOCAL_FINISH) >= 69
    BOOST_PP_LOCAL_MACRO(69)
# endif
# if (BOOST_PP_LOCAL_START) <= 70 && (BOOST_PP_LOCAL_FINISH) >= 70
    BOOST_PP_LOCAL_MACRO(70)
# endif
# if (BOOST_PP_LOCAL_START) <= 71 && (BOOST_PP_LOCAL_FINISH) >= 71
    BOOST_PP_LOCAL_MACRO(71)
# endif
# if (BOOST_PP_LOCAL_START) <= 72 && (BOOST_PP_LOCAL_FINISH) >= 72
    BOOST_PP_LOCAL_MACRO(72)
# endif
# if (BOOST_PP_LOCAL_START) <= 73 && (BOOST_PP_LOCAL_FINISH) >= 73
    BOOST_PP_LOCAL_MACRO(73)
# endif
# if (BOOST_PP_LOCAL_START) <= 74 && (BOOST_PP_LOCAL_FINISH) >= 74
    BOOST_PP_LOCAL_MACRO(74)
# endif
# if (BOOST_PP_LOCAL_START) <= 75 && (BOOST_PP_LOCAL_FINISH) >= 75
    BOOST_PP_LOCAL_MACRO(75)
# endif
# if (BOOST_PP_LOCAL_START) <= 76 && (BOOST_PP_LOCAL_FINISH) >= 76
    BOOST_PP_LOCAL_MACRO(76)
# endif
# if (BOOST_PP_LOCAL_START) <= 77 && (BOOST_PP_LOCAL_FINISH) >= 77
    BOOST_PP_LOCAL_MACRO(77)
# endif
# if (BOOST_PP_LOCAL_START) <= 78 && (BOOST_PP_LOCAL_FINISH) >= 78
    BOOST_PP_LOCAL_MACRO(78)
# endif
# if (BOOST_PP_LOCAL_START) <= 79 && (BOOST_PP_LOCAL_FINISH) >= 79
    BOOST_PP_LOCAL_MACRO(79)
# endif
# if (BOOST_PP_LOCAL_START) <= 80 && (BOOST_PP_LOCAL_FINISH) >= 80
    BOOST_PP_LOCAL_MACRO(80)
# endif
# if (BOOST_PP_LOCAL_START) <= 81 && (BOOST_PP_LOCAL_FINISH) >= 81
    BOOST_PP_LOCAL_MACRO(81)
# endif
# if (BOOST_PP_LOCAL_START) <= 82 && (BOOST_PP_LOCAL_FINISH) >= 82
    BOOST_PP_LOCAL_MACRO(82)
# endif
# if (BOOST_PP_LOCAL_START) <= 83 && (BOOST_PP_LOCAL_FINISH) >= 83
    BOOST_PP_LOCAL_MACRO(83)
# endif
# if (BOOST_PP_LOCAL_START) <= 84 && (BOOST_PP_LOCAL_FINISH) >= 84
    BOOST_PP_LOCAL_MACRO(84)
# endif
# if (BOOST_PP_LOCAL_START) <= 85 && (BOOST_PP_LOCAL_FINISH) >= 85
    BOOST_PP_LOCAL_MACRO(85)
# endif
# if (BOOST_PP_LOCAL_START) <= 86 && (BOOST_PP_LOCAL_FINISH) >= 86
    BOOST_PP_LOCAL_MACRO(86)
# endif
# if (BOOST_PP_LOCAL_START) <= 87 && (BOOST_PP_LOCAL_FINISH) >= 87
    BOOST_PP_LOCAL_MACRO(87)
# endif
# if (BOOST_PP_LOCAL_START) <= 88 && (BOOST_PP_LOCAL_FINISH) >= 88
    BOOST_PP_LOCAL_MACRO(88)
# endif
# if (BOOST_PP_LOCAL_START) <= 89 && (BOOST_PP_LOCAL_FINISH) >= 89
    BOOST_PP_LOCAL_MACRO(89)
# endif
# if (BOOST_PP_LOCAL_START) <= 90 && (BOOST_PP_LOCAL_FINISH) >= 90
    BOOST_PP_LOCAL_MACRO(90)
# endif
# if (BOOST_PP_LOCAL_START) <= 91 && (BOOST_PP_LOCAL_FINISH) >= 91
    BOOST_PP_LOCAL_MACRO(91)
# endif
# if (BOOST_PP_LOCAL_START) <= 92 && (BOOST_PP_LOCAL_FINISH) >= 92
    BOOST_PP_LOCAL_MACRO(92)
# endif
# if (BOOST_PP_LOCAL_START) <= 93 && (BOOST_PP_LOCAL_FINISH) >= 93
    BOOST_PP_LOCAL_MACRO(93)
# endif
# if (BOOST_PP_LOCAL_START) <= 94 && (BOOST_PP_LOCAL_FINISH) >= 94
    BOOST_PP_LOCAL_MACRO(94)
# endif
# if (BOOST_PP_LOCAL_START) <= 95 && (BOOST_PP_LOCAL_FINISH) >= 95
    BOOST_PP_LOCAL_MACRO(95)
# endif
# if (BOOST_PP_LOCAL_START) <= 96 && (BOOST_PP_LOCAL_FINISH) >= 96
    BOOST_PP_LOCAL_MACRO(96)
# endif
# if (BOOST_PP_LOCAL_START) <= 97 && (BOOST_PP_LOCAL_FINISH) >= 97
    BOOST_PP_LOCAL_MACRO(97)
# endif
# if (BOOST_PP_LOCAL_START) <= 98 && (BOOST_PP_LOCAL_FINISH) >= 98
    BOOST_PP_LOCAL_MACRO(98)
# endif
# if (BOOST_PP_LOCAL_START) <= 99 && (BOOST_PP_LOCAL_FINISH) >= 99
    BOOST_PP_LOCAL_MACRO(99)
# endif
# if (BOOST_PP_LOCAL_START) <= 100 && (BOOST_PP_LOCAL_FINISH) >= 100
    BOOST_PP_LOCAL_MACRO(100)
# endif
# if (BOOST_PP_LOCAL_START) <= 101 && (BOOST_PP_LOCAL_FINISH) >= 101
    BOOST_PP_LOCAL_MACRO(101)
# endif
# if (BOOST_PP_LOCAL_START) <= 102 && (BOOST_PP_LOCAL_FINISH) >= 102
    BOOST_PP_LOCAL_MACRO(102)
# endif
# if (BOOST_PP_LOCAL_START) <= 103 && (BOOST_PP_LOCAL_FINISH) >= 103
    BOOST_PP_LOCAL_MACRO(103)
# endif
# if (BOOST_PP_LOCAL_START) <= 104 && (BOOST_PP_LOCAL_FINISH) >= 104
    BOOST_PP_LOCAL_MACRO(104)
# endif
# if (BOOST_PP_LOCAL_START) <= 105 && (BOOST_PP_LOCAL_FINISH) >= 105
    BOOST_PP_LOCAL_MACRO(105)
# endif
# if (BOOST_PP_LOCAL_START) <= 106 && (BOOST_PP_LOCAL_FINISH) >= 106
    BOOST_PP_LOCAL_MACRO(106)
# endif
# if (BOOST_PP_LOCAL_START) <= 107 && (BOOST_PP_LOCAL_FINISH) >= 107
    BOOST_PP_LOCAL_MACRO(107)
# endif
# if (BOOST_PP_LOCAL_START) <= 108 && (BOOST_PP_LOCAL_FINISH) >= 108
    BOOST_PP_LOCAL_MACRO(108)
# endif
# if (BOOST_PP_LOCAL_START) <= 109 && (BOOST_PP_LOCAL_FINISH) >= 109
    BOOST_PP_LOCAL_MACRO(109)
# endif
# if (BOOST_PP_LOCAL_START) <= 110 && (BOOST_PP_LOCAL_FINISH) >= 110
    BOOST_PP_LOCAL_MACRO(110)
# endif
# if (BOOST_PP_LOCAL_START) <= 111 && (BOOST_PP_LOCAL_FINISH) >= 111
    BOOST_PP_LOCAL_MACRO(111)
# endif
# if (BOOST_PP_LOCAL_START) <= 112 && (BOOST_PP_LOCAL_FINISH) >= 112
    BOOST_PP_LOCAL_MACRO(112)
# endif
# if (BOOST_PP_LOCAL_START) <= 113 && (BOOST_PP_LOCAL_FINISH) >= 113
    BOOST_PP_LOCAL_MACRO(113)
# endif
# if (BOOST_PP_LOCAL_START) <= 114 && (BOOST_PP_LOCAL_FINISH) >= 114
    BOOST_PP_LOCAL_MACRO(114)
# endif
# if (BOOST_PP_LOCAL_START) <= 115 && (BOOST_PP_LOCAL_FINISH) >= 115
    BOOST_PP_LOCAL_MACRO(115)
# endif
# if (BOOST_PP_LOCAL_START) <= 116 && (BOOST_PP_LOCAL_FINISH) >= 116
    BOOST_PP_LOCAL_MACRO(116)
# endif
# if (BOOST_PP_LOCAL_START) <= 117 && (BOOST_PP_LOCAL_FINISH) >= 117
    BOOST_PP_LOCAL_MACRO(117)
# endif
# if (BOOST_PP_LOCAL_START) <= 118 && (BOOST_PP_LOCAL_FINISH) >= 118
    BOOST_PP_LOCAL_MACRO(118)
# endif
# if (BOOST_PP_LOCAL_START) <= 119 && (BOOST_PP_LOCAL_FINISH) >= 119
    BOOST_PP_LOCAL_MACRO(119)
# endif
# if (BOOST_PP_LOCAL_START) <= 120 && (BOOST_PP_LOCAL_FINISH) >= 120
    BOOST_PP_LOCAL_MACRO(120)
# endif
# if (BOOST_PP_LOCAL_START) <= 121 && (BOOST_PP_LOCAL_FINISH) >= 121
    BOOST_PP_LOCAL_MACRO(121)
# endif
# if (BOOST_PP_LOCAL_START) <= 122 && (BOOST_PP_LOCAL_FINISH) >= 122
    BOOST_PP_LOCAL_MACRO(122)
# endif
# if (BOOST_PP_LOCAL_START) <= 123 && (BOOST_PP_LOCAL_FINISH) >= 123
    BOOST_PP_LOCAL_MACRO(123)
# endif
# if (BOOST_PP_LOCAL_START) <= 124 && (BOOST_PP_LOCAL_FINISH) >= 124
    BOOST_PP_LOCAL_MACRO(124)
# endif
# if (BOOST_PP_LOCAL_START) <= 125 && (BOOST_PP_LOCAL_FINISH) >= 125
    BOOST_PP_LOCAL_MACRO(125)
# endif
# if (BOOST_PP_LOCAL_START) <= 126 && (BOOST_PP_LOCAL_FINISH) >= 126
    BOOST_PP_LOCAL_MACRO(126)
# endif
# if (BOOST_PP_LOCAL_START) <= 127 && (BOOST_PP_LOCAL_FINISH) >= 127
    BOOST_PP_LOCAL_MACRO(127)
# endif
# if (BOOST_PP_LOCAL_START) <= 128 && (BOOST_PP_LOCAL_FINISH) >= 128
    BOOST_PP_LOCAL_MACRO(128)
# endif
# if (BOOST_PP_LOCAL_START) <= 129 && (BOOST_PP_LOCAL_FINISH) >= 129
    BOOST_PP_LOCAL_MACRO(129)
# endif
# if (BOOST_PP_LOCAL_START) <= 130 && (BOOST_PP_LOCAL_FINISH) >= 130
    BOOST_PP_LOCAL_MACRO(130)
# endif
# if (BOOST_PP_LOCAL_START) <= 131 && (BOOST_PP_LOCAL_FINISH) >= 131
    BOOST_PP_LOCAL_MACRO(131)
# endif
# if (BOOST_PP_LOCAL_START) <= 132 && (BOOST_PP_LOCAL_FINISH) >= 132
    BOOST_PP_LOCAL_MACRO(132)
# endif
# if (BOOST_PP_LOCAL_START) <= 133 && (BOOST_PP_LOCAL_FINISH) >= 133
    BOOST_PP_LOCAL_MACRO(133)
# endif
# if (BOOST_PP_LOCAL_START) <= 134 && (BOOST_PP_LOCAL_FINISH) >= 134
    BOOST_PP_LOCAL_MACRO(134)
# endif
# if (BOOST_PP_LOCAL_START) <= 135 && (BOOST_PP_LOCAL_FINISH) >= 135
    BOOST_PP_LOCAL_MACRO(135)
# endif
# if (BOOST_PP_LOCAL_START) <= 136 && (BOOST_PP_LOCAL_FINISH) >= 136
    BOOST_PP_LOCAL_MACRO(136)
# endif
# if (BOOST_PP_LOCAL_START) <= 137 && (BOOST_PP_LOCAL_FINISH) >= 137
    BOOST_PP_LOCAL_MACRO(137)
# endif
# if (BOOST_PP_LOCAL_START) <= 138 && (BOOST_PP_LOCAL_FINISH) >= 138
    BOOST_PP_LOCAL_MACRO(138)
# endif
# if (BOOST_PP_LOCAL_START) <= 139 && (BOOST_PP_LOCAL_FINISH) >= 139
    BOOST_PP_LOCAL_MACRO(139)
# endif
# if (BOOST_PP_LOCAL_START) <= 140 && (BOOST_PP_LOCAL_FINISH) >= 140
    BOOST_PP_LOCAL_MACRO(140)
# endif
# if (BOOST_PP_LOCAL_START) <= 141 && (BOOST_PP_LOCAL_FINISH) >= 141
    BOOST_PP_LOCAL_MACRO(141)
# endif
# if (BOOST_PP_LOCAL_START) <= 142 && (BOOST_PP_LOCAL_FINISH) >= 142
    BOOST_PP_LOCAL_MACRO(142)
# endif
# if (BOOST_PP_LOCAL_START) <= 143 && (BOOST_PP_LOCAL_FINISH) >= 143
    BOOST_PP_LOCAL_MACRO(143)
# endif
# if (BOOST_PP_LOCAL_START) <= 144 && (BOOST_PP_LOCAL_FINISH) >= 144
    BOOST_PP_LOCAL_MACRO(144)
# endif
# if (BOOST_PP_LOCAL_START) <= 145 && (BOOST_PP_LOCAL_FINISH) >= 145
    BOOST_PP_LOCAL_MACRO(145)
# endif
# if (BOOST_PP_LOCAL_START) <= 146 && (BOOST_PP_LOCAL_FINISH) >= 146
    BOOST_PP_LOCAL_MACRO(146)
# endif
# if (BOOST_PP_LOCAL_START) <= 147 && (BOOST_PP_LOCAL_FINISH) >= 147
    BOOST_PP_LOCAL_MACRO(147)
# endif
# if (BOOST_PP_LOCAL_START) <= 148 && (BOOST_PP_LOCAL_FINISH) >= 148
    BOOST_PP_LOCAL_MACRO(148)
# endif
# if (BOOST_PP_LOCAL_START) <= 149 && (BOOST_PP_LOCAL_FINISH) >= 149
    BOOST_PP_LOCAL_MACRO(149)
# endif
# if (BOOST_PP_LOCAL_START) <= 150 && (BOOST_PP_LOCAL_FINISH) >= 150
    BOOST_PP_LOCAL_MACRO(150)
# endif
# if (BOOST_PP_LOCAL_START) <= 151 && (BOOST_PP_LOCAL_FINISH) >= 151
    BOOST_PP_LOCAL_MACRO(151)
# endif
# if (BOOST_PP_LOCAL_START) <= 152 && (BOOST_PP_LOCAL_FINISH) >= 152
    BOOST_PP_LOCAL_MACRO(152)
# endif
# if (BOOST_PP_LOCAL_START) <= 153 && (BOOST_PP_LOCAL_FINISH) >= 153
    BOOST_PP_LOCAL_MACRO(153)
# endif
# if (BOOST_PP_LOCAL_START) <= 154 && (BOOST_PP_LOCAL_FINISH) >= 154
    BOOST_PP_LOCAL_MACRO(154)
# endif
# if (BOOST_PP_LOCAL_START) <= 155 && (BOOST_PP_LOCAL_FINISH) >= 155
    BOOST_PP_LOCAL_MACRO(155)
# endif
# if (BOOST_PP_LOCAL_START) <= 156 && (BOOST_PP_LOCAL_FINISH) >= 156
    BOOST_PP_LOCAL_MACRO(156)
# endif
# if (BOOST_PP_LOCAL_START) <= 157 && (BOOST_PP_LOCAL_FINISH) >= 157
    BOOST_PP_LOCAL_MACRO(157)
# endif
# if (BOOST_PP_LOCAL_START) <= 158 && (BOOST_PP_LOCAL_FINISH) >= 158
    BOOST_PP_LOCAL_MACRO(158)
# endif
# if (BOOST_PP_LOCAL_START) <= 159 && (BOOST_PP_LOCAL_FINISH) >= 159
    BOOST_PP_LOCAL_MACRO(159)
# endif
# if (BOOST_PP_LOCAL_START) <= 160 && (BOOST_PP_LOCAL_FINISH) >= 160
    BOOST_PP_LOCAL_MACRO(160)
# endif
# if (BOOST_PP_LOCAL_START) <= 161 && (BOOST_PP_LOCAL_FINISH) >= 161
    BOOST_PP_LOCAL_MACRO(161)
# endif
# if (BOOST_PP_LOCAL_START) <= 162 && (BOOST_PP_LOCAL_FINISH) >= 162
    BOOST_PP_LOCAL_MACRO(162)
# endif
# if (BOOST_PP_LOCAL_START) <= 163 && (BOOST_PP_LOCAL_FINISH) >= 163
    BOOST_PP_LOCAL_MACRO(163)
# endif
# if (BOOST_PP_LOCAL_START) <= 164 && (BOOST_PP_LOCAL_FINISH) >= 164
    BOOST_PP_LOCAL_MACRO(164)
# endif
# if (BOOST_PP_LOCAL_START) <= 165 && (BOOST_PP_LOCAL_FINISH) >= 165
    BOOST_PP_LOCAL_MACRO(165)
# endif
# if (BOOST_PP_LOCAL_START) <= 166 && (BOOST_PP_LOCAL_FINISH) >= 166
    BOOST_PP_LOCAL_MACRO(166)
# endif
# if (BOOST_PP_LOCAL_START) <= 167 && (BOOST_PP_LOCAL_FINISH) >= 167
    BOOST_PP_LOCAL_MACRO(167)
# endif
# if (BOOST_PP_LOCAL_START) <= 168 && (BOOST_PP_LOCAL_FINISH) >= 168
    BOOST_PP_LOCAL_MACRO(168)
# endif
# if (BOOST_PP_LOCAL_START) <= 169 && (BOOST_PP_LOCAL_FINISH) >= 169
    BOOST_PP_LOCAL_MACRO(169)
# endif
# if (BOOST_PP_LOCAL_START) <= 170 && (BOOST_PP_LOCAL_FINISH) >= 170
    BOOST_PP_LOCAL_MACRO(170)
# endif
# if (BOOST_PP_LOCAL_START) <= 171 && (BOOST_PP_LOCAL_FINISH) >= 171
    BOOST_PP_LOCAL_MACRO(171)
# endif
# if (BOOST_PP_LOCAL_START) <= 172 && (BOOST_PP_LOCAL_FINISH) >= 172
    BOOST_PP_LOCAL_MACRO(172)
# endif
# if (BOOST_PP_LOCAL_START) <= 173 && (BOOST_PP_LOCAL_FINISH) >= 173
    BOOST_PP_LOCAL_MACRO(173)
# endif
# if (BOOST_PP_LOCAL_START) <= 174 && (BOOST_PP_LOCAL_FINISH) >= 174
    BOOST_PP_LOCAL_MACRO(174)
# endif
# if (BOOST_PP_LOCAL_START) <= 175 && (BOOST_PP_LOCAL_FINISH) >= 175
    BOOST_PP_LOCAL_MACRO(175)
# endif
# if (BOOST_PP_LOCAL_START) <= 176 && (BOOST_PP_LOCAL_FINISH) >= 176
    BOOST_PP_LOCAL_MACRO(176)
# endif
# if (BOOST_PP_LOCAL_START) <= 177 && (BOOST_PP_LOCAL_FINISH) >= 177
    BOOST_PP_LOCAL_MACRO(177)
# endif
# if (BOOST_PP_LOCAL_START) <= 178 && (BOOST_PP_LOCAL_FINISH) >= 178
    BOOST_PP_LOCAL_MACRO(178)
# endif
# if (BOOST_PP_LOCAL_START) <= 179 && (BOOST_PP_LOCAL_FINISH) >= 179
    BOOST_PP_LOCAL_MACRO(179)
# endif
# if (BOOST_PP_LOCAL_START) <= 180 && (BOOST_PP_LOCAL_FINISH) >= 180
    BOOST_PP_LOCAL_MACRO(180)
# endif
# if (BOOST_PP_LOCAL_START) <= 181 && (BOOST_PP_LOCAL_FINISH) >= 181
    BOOST_PP_LOCAL_MACRO(181)
# endif
# if (BOOST_PP_LOCAL_START) <= 182 && (BOOST_PP_LOCAL_FINISH) >= 182
    BOOST_PP_LOCAL_MACRO(182)
# endif
# if (BOOST_PP_LOCAL_START) <= 183 && (BOOST_PP_LOCAL_FINISH) >= 183
    BOOST_PP_LOCAL_MACRO(183)
# endif
# if (BOOST_PP_LOCAL_START) <= 184 && (BOOST_PP_LOCAL_FINISH) >= 184
    BOOST_PP_LOCAL_MACRO(184)
# endif
# if (BOOST_PP_LOCAL_START) <= 185 && (BOOST_PP_LOCAL_FINISH) >= 185
    BOOST_PP_LOCAL_MACRO(185)
# endif
# if (BOOST_PP_LOCAL_START) <= 186 && (BOOST_PP_LOCAL_FINISH) >= 186
    BOOST_PP_LOCAL_MACRO(186)
# endif
# if (BOOST_PP_LOCAL_START) <= 187 && (BOOST_PP_LOCAL_FINISH) >= 187
    BOOST_PP_LOCAL_MACRO(187)
# endif
# if (BOOST_PP_LOCAL_START) <= 188 && (BOOST_PP_LOCAL_FINISH) >= 188
    BOOST_PP_LOCAL_MACRO(188)
# endif
# if (BOOST_PP_LOCAL_START) <= 189 && (BOOST_PP_LOCAL_FINISH) >= 189
    BOOST_PP_LOCAL_MACRO(189)
# endif
# if (BOOST_PP_LOCAL_START) <= 190 && (BOOST_PP_LOCAL_FINISH) >= 190
    BOOST_PP_LOCAL_MACRO(190)
# endif
# if (BOOST_PP_LOCAL_START) <= 191 && (BOOST_PP_LOCAL_FINISH) >= 191
    BOOST_PP_LOCAL_MACRO(191)
# endif
# if (BOOST_PP_LOCAL_START) <= 192 && (BOOST_PP_LOCAL_FINISH) >= 192
    BOOST_PP_LOCAL_MACRO(192)
# endif
# if (BOOST_PP_LOCAL_START) <= 193 && (BOOST_PP_LOCAL_FINISH) >= 193
    BOOST_PP_LOCAL_MACRO(193)
# endif
# if (BOOST_PP_LOCAL_START) <= 194 && (BOOST_PP_LOCAL_FINISH) >= 194
    BOOST_PP_LOCAL_MACRO(194)
# endif
# if (BOOST_PP_LOCAL_START) <= 195 && (BOOST_PP_LOCAL_FINISH) >= 195
    BOOST_PP_LOCAL_MACRO(195)
# endif
# if (BOOST_PP_LOCAL_START) <= 196 && (BOOST_PP_LOCAL_FINISH) >= 196
    BOOST_PP_LOCAL_MACRO(196)
# endif
# if (BOOST_PP_LOCAL_START) <= 197 && (BOOST_PP_LOCAL_FINISH) >= 197
    BOOST_PP_LOCAL_MACRO(197)
# endif
# if (BOOST_PP_LOCAL_START) <= 198 && (BOOST_PP_LOCAL_FINISH) >= 198
    BOOST_PP_LOCAL_MACRO(198)
# endif
# if (BOOST_PP_LOCAL_START) <= 199 && (BOOST_PP_LOCAL_FINISH) >= 199
    BOOST_PP_LOCAL_MACRO(199)
# endif
# if (BOOST_PP_LOCAL_START) <= 200 && (BOOST_PP_LOCAL_FINISH) >= 200
    BOOST_PP_LOCAL_MACRO(200)
# endif
# if (BOOST_PP_LOCAL_START) <= 201 && (BOOST_PP_LOCAL_FINISH) >= 201
    BOOST_PP_LOCAL_MACRO(201)
# endif
# if (BOOST_PP_LOCAL_START) <= 202 && (BOOST_PP_LOCAL_FINISH) >= 202
    BOOST_PP_LOCAL_MACRO(202)
# endif
# if (BOOST_PP_LOCAL_START) <= 203 && (BOOST_PP_LOCAL_FINISH) >= 203
    BOOST_PP_LOCAL_MACRO(203)
# endif
# if (BOOST_PP_LOCAL_START) <= 204 && (BOOST_PP_LOCAL_FINISH) >= 204
    BOOST_PP_LOCAL_MACRO(204)
# endif
# if (BOOST_PP_LOCAL_START) <= 205 && (BOOST_PP_LOCAL_FINISH) >= 205
    BOOST_PP_LOCAL_MACRO(205)
# endif
# if (BOOST_PP_LOCAL_START) <= 206 && (BOOST_PP_LOCAL_FINISH) >= 206
    BOOST_PP_LOCAL_MACRO(206)
# endif
# if (BOOST_PP_LOCAL_START) <= 207 && (BOOST_PP_LOCAL_FINISH) >= 207
    BOOST_PP_LOCAL_MACRO(207)
# endif
# if (BOOST_PP_LOCAL_START) <= 208 && (BOOST_PP_LOCAL_FINISH) >= 208
    BOOST_PP_LOCAL_MACRO(208)
# endif
# if (BOOST_PP_LOCAL_START) <= 209 && (BOOST_PP_LOCAL_FINISH) >= 209
    BOOST_PP_LOCAL_MACRO(209)
# endif
# if (BOOST_PP_LOCAL_START) <= 210 && (BOOST_PP_LOCAL_FINISH) >= 210
    BOOST_PP_LOCAL_MACRO(210)
# endif
# if (BOOST_PP_LOCAL_START) <= 211 && (BOOST_PP_LOCAL_FINISH) >= 211
    BOOST_PP_LOCAL_MACRO(211)
# endif
# if (BOOST_PP_LOCAL_START) <= 212 && (BOOST_PP_LOCAL_FINISH) >= 212
    BOOST_PP_LOCAL_MACRO(212)
# endif
# if (BOOST_PP_LOCAL_START) <= 213 && (BOOST_PP_LOCAL_FINISH) >= 213
    BOOST_PP_LOCAL_MACRO(213)
# endif
# if (BOOST_PP_LOCAL_START) <= 214 && (BOOST_PP_LOCAL_FINISH) >= 214
    BOOST_PP_LOCAL_MACRO(214)
# endif
# if (BOOST_PP_LOCAL_START) <= 215 && (BOOST_PP_LOCAL_FINISH) >= 215
    BOOST_PP_LOCAL_MACRO(215)
# endif
# if (BOOST_PP_LOCAL_START) <= 216 && (BOOST_PP_LOCAL_FINISH) >= 216
    BOOST_PP_LOCAL_MACRO(216)
# endif
# if (BOOST_PP_LOCAL_START) <= 217 && (BOOST_PP_LOCAL_FINISH) >= 217
    BOOST_PP_LOCAL_MACRO(217)
# endif
# if (BOOST_PP_LOCAL_START) <= 218 && (BOOST_PP_LOCAL_FINISH) >= 218
    BOOST_PP_LOCAL_MACRO(218)
# endif
# if (BOOST_PP_LOCAL_START) <= 219 && (BOOST_PP_LOCAL_FINISH) >= 219
    BOOST_PP_LOCAL_MACRO(219)
# endif
# if (BOOST_PP_LOCAL_START) <= 220 && (BOOST_PP_LOCAL_FINISH) >= 220
    BOOST_PP_LOCAL_MACRO(220)
# endif
# if (BOOST_PP_LOCAL_START) <= 221 && (BOOST_PP_LOCAL_FINISH) >= 221
    BOOST_PP_LOCAL_MACRO(221)
# endif
# if (BOOST_PP_LOCAL_START) <= 222 && (BOOST_PP_LOCAL_FINISH) >= 222
    BOOST_PP_LOCAL_MACRO(222)
# endif
# if (BOOST_PP_LOCAL_START) <= 223 && (BOOST_PP_LOCAL_FINISH) >= 223
    BOOST_PP_LOCAL_MACRO(223)
# endif
# if (BOOST_PP_LOCAL_START) <= 224 && (BOOST_PP_LOCAL_FINISH) >= 224
    BOOST_PP_LOCAL_MACRO(224)
# endif
# if (BOOST_PP_LOCAL_START) <= 225 && (BOOST_PP_LOCAL_FINISH) >= 225
    BOOST_PP_LOCAL_MACRO(225)
# endif
# if (BOOST_PP_LOCAL_START) <= 226 && (BOOST_PP_LOCAL_FINISH) >= 226
    BOOST_PP_LOCAL_MACRO(226)
# endif
# if (BOOST_PP_LOCAL_START) <= 227 && (BOOST_PP_LOCAL_FINISH) >= 227
    BOOST_PP_LOCAL_MACRO(227)
# endif
# if (BOOST_PP_LOCAL_START) <= 228 && (BOOST_PP_LOCAL_FINISH) >= 228
    BOOST_PP_LOCAL_MACRO(228)
# endif
# if (BOOST_PP_LOCAL_START) <= 229 && (BOOST_PP_LOCAL_FINISH) >= 229
    BOOST_PP_LOCAL_MACRO(229)
# endif
# if (BOOST_PP_LOCAL_START) <= 230 && (BOOST_PP_LOCAL_FINISH) >= 230
    BOOST_PP_LOCAL_MACRO(230)
# endif
# if (BOOST_PP_LOCAL_START) <= 231 && (BOOST_PP_LOCAL_FINISH) >= 231
    BOOST_PP_LOCAL_MACRO(231)
# endif
# if (BOOST_PP_LOCAL_START) <= 232 && (BOOST_PP_LOCAL_FINISH) >= 232
    BOOST_PP_LOCAL_MACRO(232)
# endif
# if (BOOST_PP_LOCAL_START) <= 233 && (BOOST_PP_LOCAL_FINISH) >= 233
    BOOST_PP_LOCAL_MACRO(233)
# endif
# if (BOOST_PP_LOCAL_START) <= 234 && (BOOST_PP_LOCAL_FINISH) >= 234
    BOOST_PP_LOCAL_MACRO(234)
# endif
# if (BOOST_PP_LOCAL_START) <= 235 && (BOOST_PP_LOCAL_FINISH) >= 235
    BOOST_PP_LOCAL_MACRO(235)
# endif
# if (BOOST_PP_LOCAL_START) <= 236 && (BOOST_PP_LOCAL_FINISH) >= 236
    BOOST_PP_LOCAL_MACRO(236)
# endif
# if (BOOST_PP_LOCAL_START) <= 237 && (BOOST_PP_LOCAL_FINISH) >= 237
    BOOST_PP_LOCAL_MACRO(237)
# endif
# if (BOOST_PP_LOCAL_START) <= 238 && (BOOST_PP_LOCAL_FINISH) >= 238
    BOOST_PP_LOCAL_MACRO(238)
# endif
# if (BOOST_PP_LOCAL_START) <= 239 && (BOOST_PP_LOCAL_FINISH) >= 239
    BOOST_PP_LOCAL_MACRO(239)
# endif
# if (BOOST_PP_LOCAL_START) <= 240 && (BOOST_PP_LOCAL_FINISH) >= 240
    BOOST_PP_LOCAL_MACRO(240)
# endif
# if (BOOST_PP_LOCAL_START) <= 241 && (BOOST_PP_LOCAL_FINISH) >= 241
    BOOST_PP_LOCAL_MACRO(241)
# endif
# if (BOOST_PP_LOCAL_START) <= 242 && (BOOST_PP_LOCAL_FINISH) >= 242
    BOOST_PP_LOCAL_MACRO(242)
# endif
# if (BOOST_PP_LOCAL_START) <= 243 && (BOOST_PP_LOCAL_FINISH) >= 243
    BOOST_PP_LOCAL_MACRO(243)
# endif
# if (BOOST_PP_LOCAL_START) <= 244 && (BOOST_PP_LOCAL_FINISH) >= 244
    BOOST_PP_LOCAL_MACRO(244)
# endif
# if (BOOST_PP_LOCAL_START) <= 245 && (BOOST_PP_LOCAL_FINISH) >= 245
    BOOST_PP_LOCAL_MACRO(245)
# endif
# if (BOOST_PP_LOCAL_START) <= 246 && (BOOST_PP_LOCAL_FINISH) >= 246
    BOOST_PP_LOCAL_MACRO(246)
# endif
# if (BOOST_PP_LOCAL_START) <= 247 && (BOOST_PP_LOCAL_FINISH) >= 247
    BOOST_PP_LOCAL_MACRO(247)
# endif
# if (BOOST_PP_LOCAL_START) <= 248 && (BOOST_PP_LOCAL_FINISH) >= 248
    BOOST_PP_LOCAL_MACRO(248)
# endif
# if (BOOST_PP_LOCAL_START) <= 249 && (BOOST_PP_LOCAL_FINISH) >= 249
    BOOST_PP_LOCAL_MACRO(249)
# endif
# if (BOOST_PP_LOCAL_START) <= 250 && (BOOST_PP_LOCAL_FINISH) >= 250
    BOOST_PP_LOCAL_MACRO(250)
# endif
# if (BOOST_PP_LOCAL_START) <= 251 && (BOOST_PP_LOCAL_FINISH) >= 251
    BOOST_PP_LOCAL_MACRO(251)
# endif
# if (BOOST_PP_LOCAL_START) <= 252 && (BOOST_PP_LOCAL_FINISH) >= 252
    BOOST_PP_LOCAL_MACRO(252)
# endif
# if (BOOST_PP_LOCAL_START) <= 253 && (BOOST_PP_LOCAL_FINISH) >= 253
    BOOST_PP_LOCAL_MACRO(253)
# endif
# if (BOOST_PP_LOCAL_START) <= 254 && (BOOST_PP_LOCAL_FINISH) >= 254
    BOOST_PP_LOCAL_MACRO(254)
# endif
# if (BOOST_PP_LOCAL_START) <= 255 && (BOOST_PP_LOCAL_FINISH) >= 255
    BOOST_PP_LOCAL_MACRO(255)
# endif
# if (BOOST_PP_LOCAL_START) <= 256 && (BOOST_PP_LOCAL_FINISH) >= 256
    BOOST_PP_LOCAL_MACRO(256)
# endif
#
# undef BOOST_PP_LOCAL_START
# undef BOOST_PP_LOCAL_FINISH
#
# undef BOOST_PP_LOCAL_MACRO
