# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.  Permission to copy, use,        *
#  *     modify, sell, and distribute this software is granted provided       *
#  *     this copyright notice appears in all copies.  This software is       *
#  *     provided "as is" without express or implied warranty, and with       *
#  *     no claim at to its suitability for any purpose.                      *
#  *                                                                          *
#  ************************************************************************** */
#
# line BOOST_PP_DETAIL_LINE()
#
# ifndef BOOST_PP_VALUE
#   error BOOST_PP:  BOOST_PP_VALUE must be set prior to including BOOST_PP_SET_LBOUND()
# endif
#
# undef BOOST_PP_ITERATION_START_4
#
# if (BOOST_PP_VALUE) == 0
#   define BOOST_PP_ITERATION_START_4 0
# elif (BOOST_PP_VALUE) == 1
#   define BOOST_PP_ITERATION_START_4 1
# elif (BOOST_PP_VALUE) == 2
#   define BOOST_PP_ITERATION_START_4 2
# elif (BOOST_PP_VALUE) == 3
#   define BOOST_PP_ITERATION_START_4 3
# elif (BOOST_PP_VALUE) == 4
#   define BOOST_PP_ITERATION_START_4 4
# elif (BOOST_PP_VALUE) == 5
#   define BOOST_PP_ITERATION_START_4 5
# elif (BOOST_PP_VALUE) == 6
#   define BOOST_PP_ITERATION_START_4 6
# elif (BOOST_PP_VALUE) == 7
#   define BOOST_PP_ITERATION_START_4 7
# elif (BOOST_PP_VALUE) == 8
#   define BOOST_PP_ITERATION_START_4 8
# elif (BOOST_PP_VALUE) == 9
#   define BOOST_PP_ITERATION_START_4 9
# elif (BOOST_PP_VALUE) == 10
#   define BOOST_PP_ITERATION_START_4 10
# elif (BOOST_PP_VALUE) == 11
#   define BOOST_PP_ITERATION_START_4 11
# elif (BOOST_PP_VALUE) == 12
#   define BOOST_PP_ITERATION_START_4 12
# elif (BOOST_PP_VALUE) == 13
#   define BOOST_PP_ITERATION_START_4 13
# elif (BOOST_PP_VALUE) == 14
#   define BOOST_PP_ITERATION_START_4 14
# elif (BOOST_PP_VALUE) == 15
#   define BOOST_PP_ITERATION_START_4 15
# elif (BOOST_PP_VALUE) == 16
#   define BOOST_PP_ITERATION_START_4 16
# elif (BOOST_PP_VALUE) == 17
#   define BOOST_PP_ITERATION_START_4 17
# elif (BOOST_PP_VALUE) == 18
#   define BOOST_PP_ITERATION_START_4 18
# elif (BOOST_PP_VALUE) == 19
#   define BOOST_PP_ITERATION_START_4 19
# elif (BOOST_PP_VALUE) == 20
#   define BOOST_PP_ITERATION_START_4 20
# elif (BOOST_PP_VALUE) == 21
#   define BOOST_PP_ITERATION_START_4 21
# elif (BOOST_PP_VALUE) == 22
#   define BOOST_PP_ITERATION_START_4 22
# elif (BOOST_PP_VALUE) == 23
#   define BOOST_PP_ITERATION_START_4 23
# elif (BOOST_PP_VALUE) == 24
#   define BOOST_PP_ITERATION_START_4 24
# elif (BOOST_PP_VALUE) == 25
#   define BOOST_PP_ITERATION_START_4 25
# elif (BOOST_PP_VALUE) == 26
#   define BOOST_PP_ITERATION_START_4 26
# elif (BOOST_PP_VALUE) == 27
#   define BOOST_PP_ITERATION_START_4 27
# elif (BOOST_PP_VALUE) == 28
#   define BOOST_PP_ITERATION_START_4 28
# elif (BOOST_PP_VALUE) == 29
#   define BOOST_PP_ITERATION_START_4 29
# elif (BOOST_PP_VALUE) == 30
#   define BOOST_PP_ITERATION_START_4 30
# elif (BOOST_PP_VALUE) == 31
#   define BOOST_PP_ITERATION_START_4 31
# elif (BOOST_PP_VALUE) == 32
#   define BOOST_PP_ITERATION_START_4 32
# elif (BOOST_PP_VALUE) == 33
#   define BOOST_PP_ITERATION_START_4 33
# elif (BOOST_PP_VALUE) == 34
#   define BOOST_PP_ITERATION_START_4 34
# elif (BOOST_PP_VALUE) == 35
#   define BOOST_PP_ITERATION_START_4 35
# elif (BOOST_PP_VALUE) == 36
#   define BOOST_PP_ITERATION_START_4 36
# elif (BOOST_PP_VALUE) == 37
#   define BOOST_PP_ITERATION_START_4 37
# elif (BOOST_PP_VALUE) == 38
#   define BOOST_PP_ITERATION_START_4 38
# elif (BOOST_PP_VALUE) == 39
#   define BOOST_PP_ITERATION_START_4 39
# elif (BOOST_PP_VALUE) == 40
#   define BOOST_PP_ITERATION_START_4 40
# elif (BOOST_PP_VALUE) == 41
#   define BOOST_PP_ITERATION_START_4 41
# elif (BOOST_PP_VALUE) == 42
#   define BOOST_PP_ITERATION_START_4 42
# elif (BOOST_PP_VALUE) == 43
#   define BOOST_PP_ITERATION_START_4 43
# elif (BOOST_PP_VALUE) == 44
#   define BOOST_PP_ITERATION_START_4 44
# elif (BOOST_PP_VALUE) == 45
#   define BOOST_PP_ITERATION_START_4 45
# elif (BOOST_PP_VALUE) == 46
#   define BOOST_PP_ITERATION_START_4 46
# elif (BOOST_PP_VALUE) == 47
#   define BOOST_PP_ITERATION_START_4 47
# elif (BOOST_PP_VALUE) == 48
#   define BOOST_PP_ITERATION_START_4 48
# elif (BOOST_PP_VALUE) == 49
#   define BOOST_PP_ITERATION_START_4 49
# elif (BOOST_PP_VALUE) == 50
#   define BOOST_PP_ITERATION_START_4 50
# elif (BOOST_PP_VALUE) == 51
#   define BOOST_PP_ITERATION_START_4 51
# elif (BOOST_PP_VALUE) == 52
#   define BOOST_PP_ITERATION_START_4 52
# elif (BOOST_PP_VALUE) == 53
#   define BOOST_PP_ITERATION_START_4 53
# elif (BOOST_PP_VALUE) == 54
#   define BOOST_PP_ITERATION_START_4 54
# elif (BOOST_PP_VALUE) == 55
#   define BOOST_PP_ITERATION_START_4 55
# elif (BOOST_PP_VALUE) == 56
#   define BOOST_PP_ITERATION_START_4 56
# elif (BOOST_PP_VALUE) == 57
#   define BOOST_PP_ITERATION_START_4 57
# elif (BOOST_PP_VALUE) == 58
#   define BOOST_PP_ITERATION_START_4 58
# elif (BOOST_PP_VALUE) == 59
#   define BOOST_PP_ITERATION_START_4 59
# elif (BOOST_PP_VALUE) == 60
#   define BOOST_PP_ITERATION_START_4 60
# elif (BOOST_PP_VALUE) == 61
#   define BOOST_PP_ITERATION_START_4 61
# elif (BOOST_PP_VALUE) == 62
#   define BOOST_PP_ITERATION_START_4 62
# elif (BOOST_PP_VALUE) == 63
#   define BOOST_PP_ITERATION_START_4 63
# elif (BOOST_PP_VALUE) == 64
#   define BOOST_PP_ITERATION_START_4 64
# elif (BOOST_PP_VALUE) == 65
#   define BOOST_PP_ITERATION_START_4 65
# elif (BOOST_PP_VALUE) == 66
#   define BOOST_PP_ITERATION_START_4 66
# elif (BOOST_PP_VALUE) == 67
#   define BOOST_PP_ITERATION_START_4 67
# elif (BOOST_PP_VALUE) == 68
#   define BOOST_PP_ITERATION_START_4 68
# elif (BOOST_PP_VALUE) == 69
#   define BOOST_PP_ITERATION_START_4 69
# elif (BOOST_PP_VALUE) == 70
#   define BOOST_PP_ITERATION_START_4 70
# elif (BOOST_PP_VALUE) == 71
#   define BOOST_PP_ITERATION_START_4 71
# elif (BOOST_PP_VALUE) == 72
#   define BOOST_PP_ITERATION_START_4 72
# elif (BOOST_PP_VALUE) == 73
#   define BOOST_PP_ITERATION_START_4 73
# elif (BOOST_PP_VALUE) == 74
#   define BOOST_PP_ITERATION_START_4 74
# elif (BOOST_PP_VALUE) == 75
#   define BOOST_PP_ITERATION_START_4 75
# elif (BOOST_PP_VALUE) == 76
#   define BOOST_PP_ITERATION_START_4 76
# elif (BOOST_PP_VALUE) == 77
#   define BOOST_PP_ITERATION_START_4 77
# elif (BOOST_PP_VALUE) == 78
#   define BOOST_PP_ITERATION_START_4 78
# elif (BOOST_PP_VALUE) == 79
#   define BOOST_PP_ITERATION_START_4 79
# elif (BOOST_PP_VALUE) == 80
#   define BOOST_PP_ITERATION_START_4 80
# elif (BOOST_PP_VALUE) == 81
#   define BOOST_PP_ITERATION_START_4 81
# elif (BOOST_PP_VALUE) == 82
#   define BOOST_PP_ITERATION_START_4 82
# elif (BOOST_PP_VALUE) == 83
#   define BOOST_PP_ITERATION_START_4 83
# elif (BOOST_PP_VALUE) == 84
#   define BOOST_PP_ITERATION_START_4 84
# elif (BOOST_PP_VALUE) == 85
#   define BOOST_PP_ITERATION_START_4 85
# elif (BOOST_PP_VALUE) == 86
#   define BOOST_PP_ITERATION_START_4 86
# elif (BOOST_PP_VALUE) == 87
#   define BOOST_PP_ITERATION_START_4 87
# elif (BOOST_PP_VALUE) == 88
#   define BOOST_PP_ITERATION_START_4 88
# elif (BOOST_PP_VALUE) == 89
#   define BOOST_PP_ITERATION_START_4 89
# elif (BOOST_PP_VALUE) == 90
#   define BOOST_PP_ITERATION_START_4 90
# elif (BOOST_PP_VALUE) == 91
#   define BOOST_PP_ITERATION_START_4 91
# elif (BOOST_PP_VALUE) == 92
#   define BOOST_PP_ITERATION_START_4 92
# elif (BOOST_PP_VALUE) == 93
#   define BOOST_PP_ITERATION_START_4 93
# elif (BOOST_PP_VALUE) == 94
#   define BOOST_PP_ITERATION_START_4 94
# elif (BOOST_PP_VALUE) == 95
#   define BOOST_PP_ITERATION_START_4 95
# elif (BOOST_PP_VALUE) == 96
#   define BOOST_PP_ITERATION_START_4 96
# elif (BOOST_PP_VALUE) == 97
#   define BOOST_PP_ITERATION_START_4 97
# elif (BOOST_PP_VALUE) == 98
#   define BOOST_PP_ITERATION_START_4 98
# elif (BOOST_PP_VALUE) == 99
#   define BOOST_PP_ITERATION_START_4 99
# elif (BOOST_PP_VALUE) == 100
#   define BOOST_PP_ITERATION_START_4 100
# elif (BOOST_PP_VALUE) == 101
#   define BOOST_PP_ITERATION_START_4 101
# elif (BOOST_PP_VALUE) == 102
#   define BOOST_PP_ITERATION_START_4 102
# elif (BOOST_PP_VALUE) == 103
#   define BOOST_PP_ITERATION_START_4 103
# elif (BOOST_PP_VALUE) == 104
#   define BOOST_PP_ITERATION_START_4 104
# elif (BOOST_PP_VALUE) == 105
#   define BOOST_PP_ITERATION_START_4 105
# elif (BOOST_PP_VALUE) == 106
#   define BOOST_PP_ITERATION_START_4 106
# elif (BOOST_PP_VALUE) == 107
#   define BOOST_PP_ITERATION_START_4 107
# elif (BOOST_PP_VALUE) == 108
#   define BOOST_PP_ITERATION_START_4 108
# elif (BOOST_PP_VALUE) == 109
#   define BOOST_PP_ITERATION_START_4 109
# elif (BOOST_PP_VALUE) == 110
#   define BOOST_PP_ITERATION_START_4 110
# elif (BOOST_PP_VALUE) == 111
#   define BOOST_PP_ITERATION_START_4 111
# elif (BOOST_PP_VALUE) == 112
#   define BOOST_PP_ITERATION_START_4 112
# elif (BOOST_PP_VALUE) == 113
#   define BOOST_PP_ITERATION_START_4 113
# elif (BOOST_PP_VALUE) == 114
#   define BOOST_PP_ITERATION_START_4 114
# elif (BOOST_PP_VALUE) == 115
#   define BOOST_PP_ITERATION_START_4 115
# elif (BOOST_PP_VALUE) == 116
#   define BOOST_PP_ITERATION_START_4 116
# elif (BOOST_PP_VALUE) == 117
#   define BOOST_PP_ITERATION_START_4 117
# elif (BOOST_PP_VALUE) == 118
#   define BOOST_PP_ITERATION_START_4 118
# elif (BOOST_PP_VALUE) == 119
#   define BOOST_PP_ITERATION_START_4 119
# elif (BOOST_PP_VALUE) == 120
#   define BOOST_PP_ITERATION_START_4 120
# elif (BOOST_PP_VALUE) == 121
#   define BOOST_PP_ITERATION_START_4 121
# elif (BOOST_PP_VALUE) == 122
#   define BOOST_PP_ITERATION_START_4 122
# elif (BOOST_PP_VALUE) == 123
#   define BOOST_PP_ITERATION_START_4 123
# elif (BOOST_PP_VALUE) == 124
#   define BOOST_PP_ITERATION_START_4 124
# elif (BOOST_PP_VALUE) == 125
#   define BOOST_PP_ITERATION_START_4 125
# elif (BOOST_PP_VALUE) == 126
#   define BOOST_PP_ITERATION_START_4 126
# elif (BOOST_PP_VALUE) == 127
#   define BOOST_PP_ITERATION_START_4 127
# elif (BOOST_PP_VALUE) == 128
#   define BOOST_PP_ITERATION_START_4 128
# elif (BOOST_PP_VALUE) == 129
#   define BOOST_PP_ITERATION_START_4 129
# elif (BOOST_PP_VALUE) == 130
#   define BOOST_PP_ITERATION_START_4 130
# elif (BOOST_PP_VALUE) == 131
#   define BOOST_PP_ITERATION_START_4 131
# elif (BOOST_PP_VALUE) == 132
#   define BOOST_PP_ITERATION_START_4 132
# elif (BOOST_PP_VALUE) == 133
#   define BOOST_PP_ITERATION_START_4 133
# elif (BOOST_PP_VALUE) == 134
#   define BOOST_PP_ITERATION_START_4 134
# elif (BOOST_PP_VALUE) == 135
#   define BOOST_PP_ITERATION_START_4 135
# elif (BOOST_PP_VALUE) == 136
#   define BOOST_PP_ITERATION_START_4 136
# elif (BOOST_PP_VALUE) == 137
#   define BOOST_PP_ITERATION_START_4 137
# elif (BOOST_PP_VALUE) == 138
#   define BOOST_PP_ITERATION_START_4 138
# elif (BOOST_PP_VALUE) == 139
#   define BOOST_PP_ITERATION_START_4 139
# elif (BOOST_PP_VALUE) == 140
#   define BOOST_PP_ITERATION_START_4 140
# elif (BOOST_PP_VALUE) == 141
#   define BOOST_PP_ITERATION_START_4 141
# elif (BOOST_PP_VALUE) == 142
#   define BOOST_PP_ITERATION_START_4 142
# elif (BOOST_PP_VALUE) == 143
#   define BOOST_PP_ITERATION_START_4 143
# elif (BOOST_PP_VALUE) == 144
#   define BOOST_PP_ITERATION_START_4 144
# elif (BOOST_PP_VALUE) == 145
#   define BOOST_PP_ITERATION_START_4 145
# elif (BOOST_PP_VALUE) == 146
#   define BOOST_PP_ITERATION_START_4 146
# elif (BOOST_PP_VALUE) == 147
#   define BOOST_PP_ITERATION_START_4 147
# elif (BOOST_PP_VALUE) == 148
#   define BOOST_PP_ITERATION_START_4 148
# elif (BOOST_PP_VALUE) == 149
#   define BOOST_PP_ITERATION_START_4 149
# elif (BOOST_PP_VALUE) == 150
#   define BOOST_PP_ITERATION_START_4 150
# elif (BOOST_PP_VALUE) == 151
#   define BOOST_PP_ITERATION_START_4 151
# elif (BOOST_PP_VALUE) == 152
#   define BOOST_PP_ITERATION_START_4 152
# elif (BOOST_PP_VALUE) == 153
#   define BOOST_PP_ITERATION_START_4 153
# elif (BOOST_PP_VALUE) == 154
#   define BOOST_PP_ITERATION_START_4 154
# elif (BOOST_PP_VALUE) == 155
#   define BOOST_PP_ITERATION_START_4 155
# elif (BOOST_PP_VALUE) == 156
#   define BOOST_PP_ITERATION_START_4 156
# elif (BOOST_PP_VALUE) == 157
#   define BOOST_PP_ITERATION_START_4 157
# elif (BOOST_PP_VALUE) == 158
#   define BOOST_PP_ITERATION_START_4 158
# elif (BOOST_PP_VALUE) == 159
#   define BOOST_PP_ITERATION_START_4 159
# elif (BOOST_PP_VALUE) == 160
#   define BOOST_PP_ITERATION_START_4 160
# elif (BOOST_PP_VALUE) == 161
#   define BOOST_PP_ITERATION_START_4 161
# elif (BOOST_PP_VALUE) == 162
#   define BOOST_PP_ITERATION_START_4 162
# elif (BOOST_PP_VALUE) == 163
#   define BOOST_PP_ITERATION_START_4 163
# elif (BOOST_PP_VALUE) == 164
#   define BOOST_PP_ITERATION_START_4 164
# elif (BOOST_PP_VALUE) == 165
#   define BOOST_PP_ITERATION_START_4 165
# elif (BOOST_PP_VALUE) == 166
#   define BOOST_PP_ITERATION_START_4 166
# elif (BOOST_PP_VALUE) == 167
#   define BOOST_PP_ITERATION_START_4 167
# elif (BOOST_PP_VALUE) == 168
#   define BOOST_PP_ITERATION_START_4 168
# elif (BOOST_PP_VALUE) == 169
#   define BOOST_PP_ITERATION_START_4 169
# elif (BOOST_PP_VALUE) == 170
#   define BOOST_PP_ITERATION_START_4 170
# elif (BOOST_PP_VALUE) == 171
#   define BOOST_PP_ITERATION_START_4 171
# elif (BOOST_PP_VALUE) == 172
#   define BOOST_PP_ITERATION_START_4 172
# elif (BOOST_PP_VALUE) == 173
#   define BOOST_PP_ITERATION_START_4 173
# elif (BOOST_PP_VALUE) == 174
#   define BOOST_PP_ITERATION_START_4 174
# elif (BOOST_PP_VALUE) == 175
#   define BOOST_PP_ITERATION_START_4 175
# elif (BOOST_PP_VALUE) == 176
#   define BOOST_PP_ITERATION_START_4 176
# elif (BOOST_PP_VALUE) == 177
#   define BOOST_PP_ITERATION_START_4 177
# elif (BOOST_PP_VALUE) == 178
#   define BOOST_PP_ITERATION_START_4 178
# elif (BOOST_PP_VALUE) == 179
#   define BOOST_PP_ITERATION_START_4 179
# elif (BOOST_PP_VALUE) == 180
#   define BOOST_PP_ITERATION_START_4 180
# elif (BOOST_PP_VALUE) == 181
#   define BOOST_PP_ITERATION_START_4 181
# elif (BOOST_PP_VALUE) == 182
#   define BOOST_PP_ITERATION_START_4 182
# elif (BOOST_PP_VALUE) == 183
#   define BOOST_PP_ITERATION_START_4 183
# elif (BOOST_PP_VALUE) == 184
#   define BOOST_PP_ITERATION_START_4 184
# elif (BOOST_PP_VALUE) == 185
#   define BOOST_PP_ITERATION_START_4 185
# elif (BOOST_PP_VALUE) == 186
#   define BOOST_PP_ITERATION_START_4 186
# elif (BOOST_PP_VALUE) == 187
#   define BOOST_PP_ITERATION_START_4 187
# elif (BOOST_PP_VALUE) == 188
#   define BOOST_PP_ITERATION_START_4 188
# elif (BOOST_PP_VALUE) == 189
#   define BOOST_PP_ITERATION_START_4 189
# elif (BOOST_PP_VALUE) == 190
#   define BOOST_PP_ITERATION_START_4 190
# elif (BOOST_PP_VALUE) == 191
#   define BOOST_PP_ITERATION_START_4 191
# elif (BOOST_PP_VALUE) == 192
#   define BOOST_PP_ITERATION_START_4 192
# elif (BOOST_PP_VALUE) == 193
#   define BOOST_PP_ITERATION_START_4 193
# elif (BOOST_PP_VALUE) == 194
#   define BOOST_PP_ITERATION_START_4 194
# elif (BOOST_PP_VALUE) == 195
#   define BOOST_PP_ITERATION_START_4 195
# elif (BOOST_PP_VALUE) == 196
#   define BOOST_PP_ITERATION_START_4 196
# elif (BOOST_PP_VALUE) == 197
#   define BOOST_PP_ITERATION_START_4 197
# elif (BOOST_PP_VALUE) == 198
#   define BOOST_PP_ITERATION_START_4 198
# elif (BOOST_PP_VALUE) == 199
#   define BOOST_PP_ITERATION_START_4 199
# elif (BOOST_PP_VALUE) == 200
#   define BOOST_PP_ITERATION_START_4 200
# elif (BOOST_PP_VALUE) == 201
#   define BOOST_PP_ITERATION_START_4 201
# elif (BOOST_PP_VALUE) == 202
#   define BOOST_PP_ITERATION_START_4 202
# elif (BOOST_PP_VALUE) == 203
#   define BOOST_PP_ITERATION_START_4 203
# elif (BOOST_PP_VALUE) == 204
#   define BOOST_PP_ITERATION_START_4 204
# elif (BOOST_PP_VALUE) == 205
#   define BOOST_PP_ITERATION_START_4 205
# elif (BOOST_PP_VALUE) == 206
#   define BOOST_PP_ITERATION_START_4 206
# elif (BOOST_PP_VALUE) == 207
#   define BOOST_PP_ITERATION_START_4 207
# elif (BOOST_PP_VALUE) == 208
#   define BOOST_PP_ITERATION_START_4 208
# elif (BOOST_PP_VALUE) == 209
#   define BOOST_PP_ITERATION_START_4 209
# elif (BOOST_PP_VALUE) == 210
#   define BOOST_PP_ITERATION_START_4 210
# elif (BOOST_PP_VALUE) == 211
#   define BOOST_PP_ITERATION_START_4 211
# elif (BOOST_PP_VALUE) == 212
#   define BOOST_PP_ITERATION_START_4 212
# elif (BOOST_PP_VALUE) == 213
#   define BOOST_PP_ITERATION_START_4 213
# elif (BOOST_PP_VALUE) == 214
#   define BOOST_PP_ITERATION_START_4 214
# elif (BOOST_PP_VALUE) == 215
#   define BOOST_PP_ITERATION_START_4 215
# elif (BOOST_PP_VALUE) == 216
#   define BOOST_PP_ITERATION_START_4 216
# elif (BOOST_PP_VALUE) == 217
#   define BOOST_PP_ITERATION_START_4 217
# elif (BOOST_PP_VALUE) == 218
#   define BOOST_PP_ITERATION_START_4 218
# elif (BOOST_PP_VALUE) == 219
#   define BOOST_PP_ITERATION_START_4 219
# elif (BOOST_PP_VALUE) == 220
#   define BOOST_PP_ITERATION_START_4 220
# elif (BOOST_PP_VALUE) == 221
#   define BOOST_PP_ITERATION_START_4 221
# elif (BOOST_PP_VALUE) == 222
#   define BOOST_PP_ITERATION_START_4 222
# elif (BOOST_PP_VALUE) == 223
#   define BOOST_PP_ITERATION_START_4 223
# elif (BOOST_PP_VALUE) == 224
#   define BOOST_PP_ITERATION_START_4 224
# elif (BOOST_PP_VALUE) == 225
#   define BOOST_PP_ITERATION_START_4 225
# elif (BOOST_PP_VALUE) == 226
#   define BOOST_PP_ITERATION_START_4 226
# elif (BOOST_PP_VALUE) == 227
#   define BOOST_PP_ITERATION_START_4 227
# elif (BOOST_PP_VALUE) == 228
#   define BOOST_PP_ITERATION_START_4 228
# elif (BOOST_PP_VALUE) == 229
#   define BOOST_PP_ITERATION_START_4 229
# elif (BOOST_PP_VALUE) == 230
#   define BOOST_PP_ITERATION_START_4 230
# elif (BOOST_PP_VALUE) == 231
#   define BOOST_PP_ITERATION_START_4 231
# elif (BOOST_PP_VALUE) == 232
#   define BOOST_PP_ITERATION_START_4 232
# elif (BOOST_PP_VALUE) == 233
#   define BOOST_PP_ITERATION_START_4 233
# elif (BOOST_PP_VALUE) == 234
#   define BOOST_PP_ITERATION_START_4 234
# elif (BOOST_PP_VALUE) == 235
#   define BOOST_PP_ITERATION_START_4 235
# elif (BOOST_PP_VALUE) == 236
#   define BOOST_PP_ITERATION_START_4 236
# elif (BOOST_PP_VALUE) == 237
#   define BOOST_PP_ITERATION_START_4 237
# elif (BOOST_PP_VALUE) == 238
#   define BOOST_PP_ITERATION_START_4 238
# elif (BOOST_PP_VALUE) == 239
#   define BOOST_PP_ITERATION_START_4 239
# elif (BOOST_PP_VALUE) == 240
#   define BOOST_PP_ITERATION_START_4 240
# elif (BOOST_PP_VALUE) == 241
#   define BOOST_PP_ITERATION_START_4 241
# elif (BOOST_PP_VALUE) == 242
#   define BOOST_PP_ITERATION_START_4 242
# elif (BOOST_PP_VALUE) == 243
#   define BOOST_PP_ITERATION_START_4 243
# elif (BOOST_PP_VALUE) == 244
#   define BOOST_PP_ITERATION_START_4 244
# elif (BOOST_PP_VALUE) == 245
#   define BOOST_PP_ITERATION_START_4 245
# elif (BOOST_PP_VALUE) == 246
#   define BOOST_PP_ITERATION_START_4 246
# elif (BOOST_PP_VALUE) == 247
#   define BOOST_PP_ITERATION_START_4 247
# elif (BOOST_PP_VALUE) == 248
#   define BOOST_PP_ITERATION_START_4 248
# elif (BOOST_PP_VALUE) == 249
#   define BOOST_PP_ITERATION_START_4 249
# elif (BOOST_PP_VALUE) == 250
#   define BOOST_PP_ITERATION_START_4 250
# elif (BOOST_PP_VALUE) == 251
#   define BOOST_PP_ITERATION_START_4 251
# elif (BOOST_PP_VALUE) == 252
#   define BOOST_PP_ITERATION_START_4 252
# elif (BOOST_PP_VALUE) == 253
#   define BOOST_PP_ITERATION_START_4 253
# elif (BOOST_PP_VALUE) == 254
#   define BOOST_PP_ITERATION_START_4 254
# elif (BOOST_PP_VALUE) == 255
#   define BOOST_PP_ITERATION_START_4 255
# elif (BOOST_PP_VALUE) == 256
#   define BOOST_PP_ITERATION_START_4 256
# else
#   error BOOST_PP:  BOOST_PP_VALUE is out of range
# endif
#
# undef BOOST_PP_VALUE
