# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.  Permission to copy, use,        *
#  *     modify, sell, and distribute this software is granted provided       *
#  *     this copyright notice appears in all copies.  This software is       *
#  *     provided "as is" without express or implied warranty, and with       *
#  *     no claim at to its suitability for any purpose.                      *
#  *                                                                          *
#  ************************************************************************** */
#
# ifndef BOOST_PP_ITERATION_BOUND
#   error BOOST_PP:  BOOST_PP_ITERATION_BOUND must be set prior to including BOOST_PP_SET_UBOUND()
# endif
#
# if BOOST_PP_ITERATION_BOUND == 0
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 0
# elif BOOST_PP_ITERATION_BOUND == 1
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 1
# elif BOOST_PP_ITERATION_BOUND == 2
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 2
# elif BOOST_PP_ITERATION_BOUND == 3
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 3
# elif BOOST_PP_ITERATION_BOUND == 4
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 4
# elif BOOST_PP_ITERATION_BOUND == 5
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 5
# elif BOOST_PP_ITERATION_BOUND == 6
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 6
# elif BOOST_PP_ITERATION_BOUND == 7
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 7
# elif BOOST_PP_ITERATION_BOUND == 8
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 8
# elif BOOST_PP_ITERATION_BOUND == 9
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 9
# elif BOOST_PP_ITERATION_BOUND == 10
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 10
# elif BOOST_PP_ITERATION_BOUND == 11
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 11
# elif BOOST_PP_ITERATION_BOUND == 12
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 12
# elif BOOST_PP_ITERATION_BOUND == 13
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 13
# elif BOOST_PP_ITERATION_BOUND == 14
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 14
# elif BOOST_PP_ITERATION_BOUND == 15
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 15
# elif BOOST_PP_ITERATION_BOUND == 16
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 16
# elif BOOST_PP_ITERATION_BOUND == 17
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 17
# elif BOOST_PP_ITERATION_BOUND == 18
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 18
# elif BOOST_PP_ITERATION_BOUND == 19
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 19
# elif BOOST_PP_ITERATION_BOUND == 20
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 20
# elif BOOST_PP_ITERATION_BOUND == 21
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 21
# elif BOOST_PP_ITERATION_BOUND == 22
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 22
# elif BOOST_PP_ITERATION_BOUND == 23
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 23
# elif BOOST_PP_ITERATION_BOUND == 24
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 24
# elif BOOST_PP_ITERATION_BOUND == 25
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 25
# elif BOOST_PP_ITERATION_BOUND == 26
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 26
# elif BOOST_PP_ITERATION_BOUND == 27
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 27
# elif BOOST_PP_ITERATION_BOUND == 28
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 28
# elif BOOST_PP_ITERATION_BOUND == 29
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 29
# elif BOOST_PP_ITERATION_BOUND == 30
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 30
# elif BOOST_PP_ITERATION_BOUND == 31
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 31
# elif BOOST_PP_ITERATION_BOUND == 32
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 32
# elif BOOST_PP_ITERATION_BOUND == 33
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 33
# elif BOOST_PP_ITERATION_BOUND == 34
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 34
# elif BOOST_PP_ITERATION_BOUND == 35
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 35
# elif BOOST_PP_ITERATION_BOUND == 36
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 36
# elif BOOST_PP_ITERATION_BOUND == 37
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 37
# elif BOOST_PP_ITERATION_BOUND == 38
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 38
# elif BOOST_PP_ITERATION_BOUND == 39
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 39
# elif BOOST_PP_ITERATION_BOUND == 40
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 40
# elif BOOST_PP_ITERATION_BOUND == 41
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 41
# elif BOOST_PP_ITERATION_BOUND == 42
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 42
# elif BOOST_PP_ITERATION_BOUND == 43
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 43
# elif BOOST_PP_ITERATION_BOUND == 44
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 44
# elif BOOST_PP_ITERATION_BOUND == 45
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 45
# elif BOOST_PP_ITERATION_BOUND == 46
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 46
# elif BOOST_PP_ITERATION_BOUND == 47
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 47
# elif BOOST_PP_ITERATION_BOUND == 48
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 48
# elif BOOST_PP_ITERATION_BOUND == 49
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 49
# elif BOOST_PP_ITERATION_BOUND == 50
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 50
# elif BOOST_PP_ITERATION_BOUND == 51
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 51
# elif BOOST_PP_ITERATION_BOUND == 52
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 52
# elif BOOST_PP_ITERATION_BOUND == 53
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 53
# elif BOOST_PP_ITERATION_BOUND == 54
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 54
# elif BOOST_PP_ITERATION_BOUND == 55
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 55
# elif BOOST_PP_ITERATION_BOUND == 56
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 56
# elif BOOST_PP_ITERATION_BOUND == 57
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 57
# elif BOOST_PP_ITERATION_BOUND == 58
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 58
# elif BOOST_PP_ITERATION_BOUND == 59
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 59
# elif BOOST_PP_ITERATION_BOUND == 60
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 60
# elif BOOST_PP_ITERATION_BOUND == 61
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 61
# elif BOOST_PP_ITERATION_BOUND == 62
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 62
# elif BOOST_PP_ITERATION_BOUND == 63
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 63
# elif BOOST_PP_ITERATION_BOUND == 64
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 64
# elif BOOST_PP_ITERATION_BOUND == 65
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 65
# elif BOOST_PP_ITERATION_BOUND == 66
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 66
# elif BOOST_PP_ITERATION_BOUND == 67
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 67
# elif BOOST_PP_ITERATION_BOUND == 68
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 68
# elif BOOST_PP_ITERATION_BOUND == 69
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 69
# elif BOOST_PP_ITERATION_BOUND == 70
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 70
# elif BOOST_PP_ITERATION_BOUND == 71
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 71
# elif BOOST_PP_ITERATION_BOUND == 72
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 72
# elif BOOST_PP_ITERATION_BOUND == 73
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 73
# elif BOOST_PP_ITERATION_BOUND == 74
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 74
# elif BOOST_PP_ITERATION_BOUND == 75
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 75
# elif BOOST_PP_ITERATION_BOUND == 76
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 76
# elif BOOST_PP_ITERATION_BOUND == 77
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 77
# elif BOOST_PP_ITERATION_BOUND == 78
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 78
# elif BOOST_PP_ITERATION_BOUND == 79
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 79
# elif BOOST_PP_ITERATION_BOUND == 80
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 80
# elif BOOST_PP_ITERATION_BOUND == 81
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 81
# elif BOOST_PP_ITERATION_BOUND == 82
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 82
# elif BOOST_PP_ITERATION_BOUND == 83
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 83
# elif BOOST_PP_ITERATION_BOUND == 84
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 84
# elif BOOST_PP_ITERATION_BOUND == 85
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 85
# elif BOOST_PP_ITERATION_BOUND == 86
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 86
# elif BOOST_PP_ITERATION_BOUND == 87
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 87
# elif BOOST_PP_ITERATION_BOUND == 88
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 88
# elif BOOST_PP_ITERATION_BOUND == 89
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 89
# elif BOOST_PP_ITERATION_BOUND == 90
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 90
# elif BOOST_PP_ITERATION_BOUND == 91
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 91
# elif BOOST_PP_ITERATION_BOUND == 92
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 92
# elif BOOST_PP_ITERATION_BOUND == 93
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 93
# elif BOOST_PP_ITERATION_BOUND == 94
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 94
# elif BOOST_PP_ITERATION_BOUND == 95
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 95
# elif BOOST_PP_ITERATION_BOUND == 96
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 96
# elif BOOST_PP_ITERATION_BOUND == 97
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 97
# elif BOOST_PP_ITERATION_BOUND == 98
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 98
# elif BOOST_PP_ITERATION_BOUND == 99
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 99
# elif BOOST_PP_ITERATION_BOUND == 100
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 100
# elif BOOST_PP_ITERATION_BOUND == 101
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 101
# elif BOOST_PP_ITERATION_BOUND == 102
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 102
# elif BOOST_PP_ITERATION_BOUND == 103
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 103
# elif BOOST_PP_ITERATION_BOUND == 104
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 104
# elif BOOST_PP_ITERATION_BOUND == 105
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 105
# elif BOOST_PP_ITERATION_BOUND == 106
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 106
# elif BOOST_PP_ITERATION_BOUND == 107
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 107
# elif BOOST_PP_ITERATION_BOUND == 108
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 108
# elif BOOST_PP_ITERATION_BOUND == 109
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 109
# elif BOOST_PP_ITERATION_BOUND == 110
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 110
# elif BOOST_PP_ITERATION_BOUND == 111
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 111
# elif BOOST_PP_ITERATION_BOUND == 112
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 112
# elif BOOST_PP_ITERATION_BOUND == 113
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 113
# elif BOOST_PP_ITERATION_BOUND == 114
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 114
# elif BOOST_PP_ITERATION_BOUND == 115
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 115
# elif BOOST_PP_ITERATION_BOUND == 116
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 116
# elif BOOST_PP_ITERATION_BOUND == 117
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 117
# elif BOOST_PP_ITERATION_BOUND == 118
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 118
# elif BOOST_PP_ITERATION_BOUND == 119
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 119
# elif BOOST_PP_ITERATION_BOUND == 120
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 120
# elif BOOST_PP_ITERATION_BOUND == 121
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 121
# elif BOOST_PP_ITERATION_BOUND == 122
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 122
# elif BOOST_PP_ITERATION_BOUND == 123
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 123
# elif BOOST_PP_ITERATION_BOUND == 124
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 124
# elif BOOST_PP_ITERATION_BOUND == 125
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 125
# elif BOOST_PP_ITERATION_BOUND == 126
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 126
# elif BOOST_PP_ITERATION_BOUND == 127
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 127
# elif BOOST_PP_ITERATION_BOUND == 128
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 128
# elif BOOST_PP_ITERATION_BOUND == 129
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 129
# elif BOOST_PP_ITERATION_BOUND == 130
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 130
# elif BOOST_PP_ITERATION_BOUND == 131
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 131
# elif BOOST_PP_ITERATION_BOUND == 132
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 132
# elif BOOST_PP_ITERATION_BOUND == 133
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 133
# elif BOOST_PP_ITERATION_BOUND == 134
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 134
# elif BOOST_PP_ITERATION_BOUND == 135
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 135
# elif BOOST_PP_ITERATION_BOUND == 136
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 136
# elif BOOST_PP_ITERATION_BOUND == 137
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 137
# elif BOOST_PP_ITERATION_BOUND == 138
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 138
# elif BOOST_PP_ITERATION_BOUND == 139
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 139
# elif BOOST_PP_ITERATION_BOUND == 140
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 140
# elif BOOST_PP_ITERATION_BOUND == 141
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 141
# elif BOOST_PP_ITERATION_BOUND == 142
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 142
# elif BOOST_PP_ITERATION_BOUND == 143
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 143
# elif BOOST_PP_ITERATION_BOUND == 144
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 144
# elif BOOST_PP_ITERATION_BOUND == 145
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 145
# elif BOOST_PP_ITERATION_BOUND == 146
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 146
# elif BOOST_PP_ITERATION_BOUND == 147
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 147
# elif BOOST_PP_ITERATION_BOUND == 148
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 148
# elif BOOST_PP_ITERATION_BOUND == 149
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 149
# elif BOOST_PP_ITERATION_BOUND == 150
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 150
# elif BOOST_PP_ITERATION_BOUND == 151
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 151
# elif BOOST_PP_ITERATION_BOUND == 152
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 152
# elif BOOST_PP_ITERATION_BOUND == 153
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 153
# elif BOOST_PP_ITERATION_BOUND == 154
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 154
# elif BOOST_PP_ITERATION_BOUND == 155
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 155
# elif BOOST_PP_ITERATION_BOUND == 156
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 156
# elif BOOST_PP_ITERATION_BOUND == 157
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 157
# elif BOOST_PP_ITERATION_BOUND == 158
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 158
# elif BOOST_PP_ITERATION_BOUND == 159
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 159
# elif BOOST_PP_ITERATION_BOUND == 160
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 160
# elif BOOST_PP_ITERATION_BOUND == 161
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 161
# elif BOOST_PP_ITERATION_BOUND == 162
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 162
# elif BOOST_PP_ITERATION_BOUND == 163
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 163
# elif BOOST_PP_ITERATION_BOUND == 164
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 164
# elif BOOST_PP_ITERATION_BOUND == 165
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 165
# elif BOOST_PP_ITERATION_BOUND == 166
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 166
# elif BOOST_PP_ITERATION_BOUND == 167
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 167
# elif BOOST_PP_ITERATION_BOUND == 168
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 168
# elif BOOST_PP_ITERATION_BOUND == 169
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 169
# elif BOOST_PP_ITERATION_BOUND == 170
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 170
# elif BOOST_PP_ITERATION_BOUND == 171
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 171
# elif BOOST_PP_ITERATION_BOUND == 172
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 172
# elif BOOST_PP_ITERATION_BOUND == 173
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 173
# elif BOOST_PP_ITERATION_BOUND == 174
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 174
# elif BOOST_PP_ITERATION_BOUND == 175
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 175
# elif BOOST_PP_ITERATION_BOUND == 176
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 176
# elif BOOST_PP_ITERATION_BOUND == 177
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 177
# elif BOOST_PP_ITERATION_BOUND == 178
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 178
# elif BOOST_PP_ITERATION_BOUND == 179
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 179
# elif BOOST_PP_ITERATION_BOUND == 180
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 180
# elif BOOST_PP_ITERATION_BOUND == 181
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 181
# elif BOOST_PP_ITERATION_BOUND == 182
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 182
# elif BOOST_PP_ITERATION_BOUND == 183
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 183
# elif BOOST_PP_ITERATION_BOUND == 184
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 184
# elif BOOST_PP_ITERATION_BOUND == 185
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 185
# elif BOOST_PP_ITERATION_BOUND == 186
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 186
# elif BOOST_PP_ITERATION_BOUND == 187
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 187
# elif BOOST_PP_ITERATION_BOUND == 188
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 188
# elif BOOST_PP_ITERATION_BOUND == 189
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 189
# elif BOOST_PP_ITERATION_BOUND == 190
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 190
# elif BOOST_PP_ITERATION_BOUND == 191
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 191
# elif BOOST_PP_ITERATION_BOUND == 192
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 192
# elif BOOST_PP_ITERATION_BOUND == 193
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 193
# elif BOOST_PP_ITERATION_BOUND == 194
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 194
# elif BOOST_PP_ITERATION_BOUND == 195
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 195
# elif BOOST_PP_ITERATION_BOUND == 196
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 196
# elif BOOST_PP_ITERATION_BOUND == 197
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 197
# elif BOOST_PP_ITERATION_BOUND == 198
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 198
# elif BOOST_PP_ITERATION_BOUND == 199
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 199
# elif BOOST_PP_ITERATION_BOUND == 200
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 200
# elif BOOST_PP_ITERATION_BOUND == 201
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 201
# elif BOOST_PP_ITERATION_BOUND == 202
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 202
# elif BOOST_PP_ITERATION_BOUND == 203
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 203
# elif BOOST_PP_ITERATION_BOUND == 204
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 204
# elif BOOST_PP_ITERATION_BOUND == 205
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 205
# elif BOOST_PP_ITERATION_BOUND == 206
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 206
# elif BOOST_PP_ITERATION_BOUND == 207
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 207
# elif BOOST_PP_ITERATION_BOUND == 208
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 208
# elif BOOST_PP_ITERATION_BOUND == 209
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 209
# elif BOOST_PP_ITERATION_BOUND == 210
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 210
# elif BOOST_PP_ITERATION_BOUND == 211
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 211
# elif BOOST_PP_ITERATION_BOUND == 212
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 212
# elif BOOST_PP_ITERATION_BOUND == 213
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 213
# elif BOOST_PP_ITERATION_BOUND == 214
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 214
# elif BOOST_PP_ITERATION_BOUND == 215
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 215
# elif BOOST_PP_ITERATION_BOUND == 216
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 216
# elif BOOST_PP_ITERATION_BOUND == 217
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 217
# elif BOOST_PP_ITERATION_BOUND == 218
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 218
# elif BOOST_PP_ITERATION_BOUND == 219
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 219
# elif BOOST_PP_ITERATION_BOUND == 220
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 220
# elif BOOST_PP_ITERATION_BOUND == 221
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 221
# elif BOOST_PP_ITERATION_BOUND == 222
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 222
# elif BOOST_PP_ITERATION_BOUND == 223
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 223
# elif BOOST_PP_ITERATION_BOUND == 224
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 224
# elif BOOST_PP_ITERATION_BOUND == 225
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 225
# elif BOOST_PP_ITERATION_BOUND == 226
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 226
# elif BOOST_PP_ITERATION_BOUND == 227
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 227
# elif BOOST_PP_ITERATION_BOUND == 228
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 228
# elif BOOST_PP_ITERATION_BOUND == 229
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 229
# elif BOOST_PP_ITERATION_BOUND == 230
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 230
# elif BOOST_PP_ITERATION_BOUND == 231
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 231
# elif BOOST_PP_ITERATION_BOUND == 232
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 232
# elif BOOST_PP_ITERATION_BOUND == 233
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 233
# elif BOOST_PP_ITERATION_BOUND == 234
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 234
# elif BOOST_PP_ITERATION_BOUND == 235
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 235
# elif BOOST_PP_ITERATION_BOUND == 236
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 236
# elif BOOST_PP_ITERATION_BOUND == 237
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 237
# elif BOOST_PP_ITERATION_BOUND == 238
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 238
# elif BOOST_PP_ITERATION_BOUND == 239
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 239
# elif BOOST_PP_ITERATION_BOUND == 240
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 240
# elif BOOST_PP_ITERATION_BOUND == 241
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 241
# elif BOOST_PP_ITERATION_BOUND == 242
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 242
# elif BOOST_PP_ITERATION_BOUND == 243
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 243
# elif BOOST_PP_ITERATION_BOUND == 244
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 244
# elif BOOST_PP_ITERATION_BOUND == 245
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 245
# elif BOOST_PP_ITERATION_BOUND == 246
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 246
# elif BOOST_PP_ITERATION_BOUND == 247
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 247
# elif BOOST_PP_ITERATION_BOUND == 248
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 248
# elif BOOST_PP_ITERATION_BOUND == 249
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 249
# elif BOOST_PP_ITERATION_BOUND == 250
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 250
# elif BOOST_PP_ITERATION_BOUND == 251
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 251
# elif BOOST_PP_ITERATION_BOUND == 252
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 252
# elif BOOST_PP_ITERATION_BOUND == 253
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 253
# elif BOOST_PP_ITERATION_BOUND == 254
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 254
# elif BOOST_PP_ITERATION_BOUND == 255
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 255
# elif BOOST_PP_ITERATION_BOUND == 256
#   undef BOOST_PP_ITERATION_FINISH_4
#   define BOOST_PP_ITERATION_FINISH_4 256
# else
#   error BOOST_PP:  BOOST_PP_ITERATION_BOUND is out of range
# endif
#
# undef BOOST_PP_ITERATION_BOUND
