

// (C) Copyright Tobias Schwinger
//
// Use, modification and distribution are subject to the Boost Software License,
// Version 1.0. (See http://www.boost.org/LICENSE_1_0.txt).

//------------------------------------------------------------------------------

#include <boost/mpl/assert.hpp>

#include <boost/mpl/at.hpp>
#include <boost/mpl/placeholders.hpp>

#include <boost/type_traits/is_same.hpp>
#include <boost/type_traits/remove_cv.hpp>

#include <boost/function_types/is_function.hpp>
#include <boost/function_types/is_function_pointer.hpp>
#include <boost/function_types/is_function_reference.hpp>
#include <boost/function_types/is_member_function_pointer.hpp>
#include <boost/function_types/is_callable_builtin.hpp>
#include <boost/function_types/is_callable_scalar.hpp>
#include <boost/function_types/is_nonmember_callable_builtin.hpp>
#include <boost/function_types/is_nonmember_callable_scalar.hpp>

#include <boost/function_types/function_arity.hpp>
#include <boost/function_types/result_type.hpp>


// The purpose of this test is to make sure the templates are instantiable with
// any type.


namespace ft = boost::function_types;
namespace mpl = boost::mpl;

using mpl::placeholders::_;

typedef int (func_a0_t)();
typedef int (func_a1_t)(int);
typedef int (*func_a0_ptr_t)();
typedef int (*func_a1_ptr_t)(int);

union union_t { };

struct class_t
{
  int member; 
  int mem_fun_a0();
  int mem_fun_a1(int);
  int mem_fun_a0_c() const;
  int mem_fun_a1_c(int) const;
  int mem_fun_a0_v() volatile;
  int mem_fun_a1_v(int) volatile;
  int mem_fun_a0_cv() const volatile;
  int mem_fun_a1_cv(int) const volatile;
};

enum enum_t { enumerator };
typedef int class_t::*mem_ptr_t;
typedef int (class_t::*mem_fun_a0_ptr_t)();
typedef int (class_t::*mem_fun_a1_ptr_t)(int);
typedef int (class_t::*mem_fun_a0_c_ptr_t)() const;
typedef int (class_t::*mem_fun_a1_c_ptr_t)(int) const;
typedef int (class_t::*mem_fun_a0_v_ptr_t)() volatile;
typedef int (class_t::*mem_fun_a1_v_ptr_t)(int) volatile;
typedef int (class_t::*mem_fun_a0_cv_ptr_t)() const volatile;
typedef int (class_t::*mem_fun_a1_cv_ptr_t)(int) const volatile;
//------------------------------------------------------------------------------
// bool
typedef bool bool_ti;
typedef const bool bool_ti_c;
typedef volatile bool bool_ti_v;
typedef  bool &bool_ti_ref;
typedef  bool *bool_ti_ptr;
typedef  bool * const bool_ti_ptr_c;
typedef  bool * volatile bool_ti_ptr_v;
typedef  bool * const volatile bool_ti_ptr_c_v;
typedef  bool (bool_ti_bndarr)[3];
typedef  bool (bool_ti_unbndarr)[];
// int
typedef int int_ti;
typedef const int int_ti_c;
typedef volatile int int_ti_v;
typedef  int &int_ti_ref;
typedef  int *int_ti_ptr;
typedef  int * const int_ti_ptr_c;
typedef  int * volatile int_ti_ptr_v;
typedef  int * const volatile int_ti_ptr_c_v;
typedef  int (int_ti_bndarr)[3];
typedef  int (int_ti_unbndarr)[];
// float
typedef float float_ti;
typedef const float float_ti_c;
typedef volatile float float_ti_v;
typedef  float &float_ti_ref;
typedef  float *float_ti_ptr;
typedef  float * const float_ti_ptr_c;
typedef  float * volatile float_ti_ptr_v;
typedef  float * const volatile float_ti_ptr_c_v;
typedef  float (float_ti_bndarr)[3];
typedef  float (float_ti_unbndarr)[];
// class_t
typedef class_t class_t_ti;
typedef const class_t class_t_ti_c;
typedef volatile class_t class_t_ti_v;
typedef  class_t &class_t_ti_ref;
typedef  class_t *class_t_ti_ptr;
typedef  class_t * const class_t_ti_ptr_c;
typedef  class_t * volatile class_t_ti_ptr_v;
typedef  class_t * const volatile class_t_ti_ptr_c_v;
typedef  class_t (class_t_ti_bndarr)[3];
typedef  class_t (class_t_ti_unbndarr)[];
// union_t
typedef union_t union_t_ti;
typedef const union_t union_t_ti_c;
typedef volatile union_t union_t_ti_v;
typedef  union_t &union_t_ti_ref;
typedef  union_t *union_t_ti_ptr;
typedef  union_t * const union_t_ti_ptr_c;
typedef  union_t * volatile union_t_ti_ptr_v;
typedef  union_t * const volatile union_t_ti_ptr_c_v;
typedef  union_t (union_t_ti_bndarr)[3];
typedef  union_t (union_t_ti_unbndarr)[];
// enum_t
typedef enum_t enum_t_ti;
typedef const enum_t enum_t_ti_c;
typedef volatile enum_t enum_t_ti_v;
typedef  enum_t &enum_t_ti_ref;
typedef  enum_t *enum_t_ti_ptr;
typedef  enum_t * const enum_t_ti_ptr_c;
typedef  enum_t * volatile enum_t_ti_ptr_v;
typedef  enum_t * const volatile enum_t_ti_ptr_c_v;
typedef  enum_t (enum_t_ti_bndarr)[3];
typedef  enum_t (enum_t_ti_unbndarr)[];
// mem_ptr_t
typedef mem_ptr_t mem_ptr_t_ti;
typedef  mem_ptr_t &mem_ptr_t_ti_ref;
typedef  mem_ptr_t *mem_ptr_t_ti_ptr;
typedef  mem_ptr_t * const mem_ptr_t_ti_ptr_c;
typedef  mem_ptr_t * volatile mem_ptr_t_ti_ptr_v;
typedef  mem_ptr_t (mem_ptr_t_ti_unbndarr)[];
// func_a0_t
typedef func_a0_t func_a0_t_ti;
// func_a1_t
typedef func_a1_t func_a1_t_ti;
// func_a0_ptr_t
typedef func_a0_ptr_t func_a0_ptr_t_ti;
typedef  func_a0_ptr_t &func_a0_ptr_t_ti_ref;
typedef  func_a0_ptr_t *func_a0_ptr_t_ti_ptr;
typedef  func_a0_ptr_t * const func_a0_ptr_t_ti_ptr_c;
typedef  func_a0_ptr_t * volatile func_a0_ptr_t_ti_ptr_v;
typedef  func_a0_ptr_t (func_a0_ptr_t_ti_unbndarr)[];
// func_a1_ptr_t
typedef func_a1_ptr_t func_a1_ptr_t_ti;
typedef  func_a1_ptr_t &func_a1_ptr_t_ti_ref;
typedef  func_a1_ptr_t *func_a1_ptr_t_ti_ptr;
typedef  func_a1_ptr_t * const func_a1_ptr_t_ti_ptr_c;
typedef  func_a1_ptr_t * volatile func_a1_ptr_t_ti_ptr_v;
typedef  func_a1_ptr_t (func_a1_ptr_t_ti_unbndarr)[];
// mem_fun_a0_ptr_t
typedef mem_fun_a0_ptr_t mem_fun_a0_ptr_t_ti;
typedef volatile mem_fun_a0_ptr_t mem_fun_a0_ptr_t_ti_v;
typedef  mem_fun_a0_ptr_t &mem_fun_a0_ptr_t_ti_ref;
typedef  mem_fun_a0_ptr_t *mem_fun_a0_ptr_t_ti_ptr;
typedef  mem_fun_a0_ptr_t * const mem_fun_a0_ptr_t_ti_ptr_c;
typedef  mem_fun_a0_ptr_t * volatile mem_fun_a0_ptr_t_ti_ptr_v;
typedef  mem_fun_a0_ptr_t (mem_fun_a0_ptr_t_ti_unbndarr)[];
// mem_fun_a1_ptr_t
typedef mem_fun_a1_ptr_t mem_fun_a1_ptr_t_ti;
typedef volatile mem_fun_a1_ptr_t mem_fun_a1_ptr_t_ti_v;
typedef  mem_fun_a1_ptr_t &mem_fun_a1_ptr_t_ti_ref;
typedef  mem_fun_a1_ptr_t *mem_fun_a1_ptr_t_ti_ptr;
typedef  mem_fun_a1_ptr_t * const mem_fun_a1_ptr_t_ti_ptr_c;
typedef  mem_fun_a1_ptr_t * volatile mem_fun_a1_ptr_t_ti_ptr_v;
typedef  mem_fun_a1_ptr_t (mem_fun_a1_ptr_t_ti_unbndarr)[];
// mem_fun_a0_c_ptr_t
typedef mem_fun_a0_c_ptr_t mem_fun_a0_c_ptr_t_ti;
typedef volatile mem_fun_a0_c_ptr_t mem_fun_a0_c_ptr_t_ti_v;
typedef  mem_fun_a0_c_ptr_t &mem_fun_a0_c_ptr_t_ti_ref;
typedef  mem_fun_a0_c_ptr_t *mem_fun_a0_c_ptr_t_ti_ptr;
typedef  mem_fun_a0_c_ptr_t * const mem_fun_a0_c_ptr_t_ti_ptr_c;
typedef  mem_fun_a0_c_ptr_t * volatile mem_fun_a0_c_ptr_t_ti_ptr_v;
typedef  mem_fun_a0_c_ptr_t (mem_fun_a0_c_ptr_t_ti_unbndarr)[];
// mem_fun_a1_c_ptr_t
typedef mem_fun_a1_c_ptr_t mem_fun_a1_c_ptr_t_ti;
typedef volatile mem_fun_a1_c_ptr_t mem_fun_a1_c_ptr_t_ti_v;
typedef  mem_fun_a1_c_ptr_t &mem_fun_a1_c_ptr_t_ti_ref;
typedef  mem_fun_a1_c_ptr_t *mem_fun_a1_c_ptr_t_ti_ptr;
typedef  mem_fun_a1_c_ptr_t * const mem_fun_a1_c_ptr_t_ti_ptr_c;
typedef  mem_fun_a1_c_ptr_t * volatile mem_fun_a1_c_ptr_t_ti_ptr_v;
typedef  mem_fun_a1_c_ptr_t (mem_fun_a1_c_ptr_t_ti_unbndarr)[];
// mem_fun_a0_v_ptr_t
typedef mem_fun_a0_v_ptr_t mem_fun_a0_v_ptr_t_ti;
typedef volatile mem_fun_a0_v_ptr_t mem_fun_a0_v_ptr_t_ti_v;
typedef  mem_fun_a0_v_ptr_t &mem_fun_a0_v_ptr_t_ti_ref;
typedef  mem_fun_a0_v_ptr_t *mem_fun_a0_v_ptr_t_ti_ptr;
typedef  mem_fun_a0_v_ptr_t * const mem_fun_a0_v_ptr_t_ti_ptr_c;
typedef  mem_fun_a0_v_ptr_t * volatile mem_fun_a0_v_ptr_t_ti_ptr_v;
typedef  mem_fun_a0_v_ptr_t (mem_fun_a0_v_ptr_t_ti_unbndarr)[];
// mem_fun_a1_v_ptr_t
typedef mem_fun_a1_v_ptr_t mem_fun_a1_v_ptr_t_ti;
typedef volatile mem_fun_a1_v_ptr_t mem_fun_a1_v_ptr_t_ti_v;
typedef  mem_fun_a1_v_ptr_t &mem_fun_a1_v_ptr_t_ti_ref;
typedef  mem_fun_a1_v_ptr_t *mem_fun_a1_v_ptr_t_ti_ptr;
typedef  mem_fun_a1_v_ptr_t * const mem_fun_a1_v_ptr_t_ti_ptr_c;
typedef  mem_fun_a1_v_ptr_t * volatile mem_fun_a1_v_ptr_t_ti_ptr_v;
typedef  mem_fun_a1_v_ptr_t (mem_fun_a1_v_ptr_t_ti_unbndarr)[];
// mem_fun_a0_cv_ptr_t
typedef mem_fun_a0_cv_ptr_t mem_fun_a0_cv_ptr_t_ti;
typedef volatile mem_fun_a0_cv_ptr_t mem_fun_a0_cv_ptr_t_ti_v;
typedef  mem_fun_a0_cv_ptr_t &mem_fun_a0_cv_ptr_t_ti_ref;
typedef  mem_fun_a0_cv_ptr_t *mem_fun_a0_cv_ptr_t_ti_ptr;
typedef  mem_fun_a0_cv_ptr_t * const mem_fun_a0_cv_ptr_t_ti_ptr_c;
typedef  mem_fun_a0_cv_ptr_t * volatile mem_fun_a0_cv_ptr_t_ti_ptr_v;
typedef  mem_fun_a0_cv_ptr_t (mem_fun_a0_cv_ptr_t_ti_unbndarr)[];
// mem_fun_a1_cv_ptr_t
typedef mem_fun_a1_cv_ptr_t mem_fun_a1_cv_ptr_t_ti;
typedef volatile mem_fun_a1_cv_ptr_t mem_fun_a1_cv_ptr_t_ti_v;
typedef  mem_fun_a1_cv_ptr_t &mem_fun_a1_cv_ptr_t_ti_ref;
typedef  mem_fun_a1_cv_ptr_t *mem_fun_a1_cv_ptr_t_ti_ptr;
typedef  mem_fun_a1_cv_ptr_t * const mem_fun_a1_cv_ptr_t_ti_ptr_c;
typedef  mem_fun_a1_cv_ptr_t * volatile mem_fun_a1_cv_ptr_t_ti_ptr_v;
typedef  mem_fun_a1_cv_ptr_t (mem_fun_a1_cv_ptr_t_ti_unbndarr)[];

//------------------------------------------------------------------------------
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< bool_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< int_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< float_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< class_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< union_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_ptr_c_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_bndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< enum_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT((ft::is_function< func_a0_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< func_a0_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_builtin< func_a0_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< func_a0_t_ti >::value,==,0);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< func_a0_t_ti >::type, int>));
BOOST_MPL_ASSERT((ft::is_function< func_a1_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< func_a1_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_builtin< func_a1_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< func_a1_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< func_a1_t_ti >::type, int>));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_function_pointer< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< func_a0_ptr_t_ti >::value,==,0);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< func_a0_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_function_pointer< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< func_a1_ptr_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< func_a1_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< func_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_ptr_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_ptr_t_ti_v >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_ptr_t_ti >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_ptr_t_ti_v >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_c_ptr_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_c_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_c_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_c_ptr_t_ti_v >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_c_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_c_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_c_ptr_t_ti >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_c_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_c_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_c_ptr_t_ti_v >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_c_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_c_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_c_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_v_ptr_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_v_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_v_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_v_ptr_t_ti_v >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_v_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_v_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_v_ptr_t_ti >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_v_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_v_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_v_ptr_t_ti_v >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_v_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_v_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_v_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_cv_ptr_t_ti >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_cv_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_cv_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a0_cv_ptr_t_ti_v >::value,==,1);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a0_cv_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a0_cv_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a0_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_cv_ptr_t_ti >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_cv_ptr_t_ti >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_cv_ptr_t_ti, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_v >));
BOOST_MPL_ASSERT_RELATION(::boost::function_types::function_arity< mem_fun_a1_cv_ptr_t_ti_v >::value,==,2);
BOOST_MPL_ASSERT((boost::is_same< ft::result_type< mem_fun_a1_cv_ptr_t_ti_v >::type, int>));
BOOST_MPL_ASSERT((boost::is_same< mpl::at_c< ft::components<mem_fun_a1_cv_ptr_t_ti_v, boost::remove_cv<_> >, 1>::type, class_t >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ref >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr_c >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_ptr_v >));
BOOST_MPL_ASSERT_NOT((ft::is_function< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_reference< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_function_pointer< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_member_function_pointer< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_builtin< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_callable_scalar< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_builtin< mem_fun_a1_cv_ptr_t_ti_unbndarr >));
BOOST_MPL_ASSERT_NOT((ft::is_nonmember_callable_scalar< mem_fun_a1_cv_ptr_t_ti_unbndarr >));

//------------------------------------------------------------------------------
// 136 types / 1144 tests.
