/*=============================================================================
    Boost.Wave: A Standard compliant C++ preprocessor library
    Example demonstrating how to preprocess the token stream generated by a
    #pragma directive
    
    http://www.boost.org/

    Copyright (c) 2001-2008 Hartmut Kaiser. Distributed under the Boost
    Software License, Version 1.0. (See accompanying file
    LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/

///////////////////////////////////////////////////////////////////////////////
//  This special pragma will be analyzed by the corresponding hook function
//  implemented in the preprocess_pragma_output_hooks policy class. This 
//  #pragma preprocesses the provided arguments in the current context.
#pragma wave pp (                                                             \
        #define M() "some text"                                               \
    )                                                                         \
    /**/
    
M() // this should produce: "some text"

