
# very basic makefile for Keyboard
#
# GNU compiler GCC
#
INCLUDES= -I../../../../../boost_1_31_0 -I../../../../ -I./
CXXFLAGS=
CXX= $(INCLUDES) $(CXXFLAGS)
LDFLAGS=
LIBS=

Keyboard : Keyboard.cpp
	g++ $(CXX) -O3 -o Keyboard Keyboard.cpp $(LDFLAGS) $(LIBS)




















