#!/bin/sh
PYTHONPATH="c:/src/docutils;c:/src/docutils/extras"
export PYTHONPATH
python c:/src/docutils/tools/rst2latex.py --documentoptions pdftex --stylesheet=docutils.sty $1 `echo $1 | sed 's/\(.*\)\..*/\1.tex/'`
